export interface CapitalAllocationPolicy {
  _id?: string;
  name: string;
  description?: string;
  reinvestmentRatio: number;
  safetyReserveRatio: number;
  personalIncomeRatio: number;
  longTermAssetRatio: number;
  isActive: boolean;
  activatedAt?: string;
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface CapitalAllocationSnapshot {
  _id?: string;
  date: string;
  policyName: string;
  totalNetProfit: number;
  
  // Phân bổ (số tiền)
  reinvestmentAmount: number;
  safetyReserveAmount: number;
  personalIncomeAmount: number;
  longTermAssetAmount: number;

  // Tỷ lệ
  reinvestmentRatio: number;
  safetyReserveRatio: number;
  personalIncomeRatio: number;
  longTermAssetRatio: number;

  // Đã sử dụng
  reinvestmentUsed: number;
  safetyReserveUsed: number;
  personalIncomeWithdrawn: number;
  longTermAssetInvested: number;

  note?: string;
  isAutoGenerated: boolean;
  createdAt?: string;
}

export interface AllocationComputation {
  date: string;
  policyName: string;
  totalNetProfit: number;
  
  reinvestmentAmount: number;
  safetyReserveAmount: number;
  personalIncomeAmount: number;
  longTermAssetAmount: number;

  reinvestmentRatio: number;
  safetyReserveRatio: number;
  personalIncomeRatio: number;
  longTermAssetRatio: number;

  cashFlowDetail?: any;
  additionalInfo?: any;
}

export interface ReinvestmentBudget {
  totalAllocated: number;
  totalUsed: number;
  available: number;
}
