#!/bin/bash

# Script để test và fix token trực tiếp trên server
echo "🔧 Facebook Token Fix Script - Direct Server Method"
echo "=================================================="

FANPAGE_ID="68ebcb48b631002b38117c82"

echo "📋 Method 1: Test bằng cách exec vào container"
echo "docker exec -it htxbachgia-shop-backend sh"
echo ""
echo "# Trong container, chạy Node.js script:"
echo "node -e \""
echo "const { MongoClient } = require('mongodb');"
echo "const uri = process.env.MONGODB_URI || 'mongodb://mongodb:27017/erp-final8';"
echo "MongoClient.connect(uri).then(async client => {"
echo "  const db = client.db();"
echo "  const fanpage = await db.collection('fanpages').findOne({_id: ObjectId('$FANPAGE_ID')});"
echo "  console.log('Fanpage:', fanpage.name);"
echo "  console.log('Token length:', fanpage.accessToken.length);"
echo "  "
echo "  // Test token"
echo "  const response = await fetch(\`https://graph.facebook.com/v19.0/me?access_token=\${fanpage.accessToken}\`);"
echo "  const result = await response.json();"
echo "  console.log('FB Response:', result);"
echo "  "
echo "  client.close();"
echo "});\""
echo ""

echo "📋 Method 2: Temporary disable auth cho debug"
echo "Tạm thời comment @UseGuards trong fanpage.controller.ts"
echo ""

echo "📋 Method 3: Lấy token mới từ Facebook"
echo "1. Vào https://developers.facebook.com/"
echo "2. Chọn app của bạn"
echo "3. Tools & Support > Access Token Tool"
echo "4. Page Access Tokens > Hộ Chiếu Toàn Quốc"
echo "5. Generate Token với permissions:"
echo "   - pages_manage_metadata"
echo "   - pages_messaging"
echo "   - pages_read_engagement"
echo "6. Copy token mới"
echo ""

echo "📋 Method 4: Update token trực tiếp trong MongoDB"
echo "docker exec -it htxbachgia-shop-backend sh"
echo "# Install mongo client nếu chưa có:"
echo "apk add --no-cache mongodb-tools"
echo ""
echo "# Connect to MongoDB và update:"
echo "mongo mongodb://mongodb:27017/erp-final8 --eval \""
echo "db.fanpages.updateOne("
echo "  {_id: ObjectId('$FANPAGE_ID')},"
echo "  {\$set: {accessToken: 'NEW_TOKEN_HERE', lastRefreshAt: new Date()}}"
echo ");\""