import type {
  AdsFoundationReviewerDocsLocalSnapshot,
  AdsFoundationReviewerDocsLocalSnapshotCompareResult,
  AdsFoundationReviewerDocsResponse,
} from './ads-foundation-reviewer-docs.service';

export const ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE: AdsFoundationReviewerDocsResponse = {
  schemaVersion: 'ads_automation_decision_foundation_read_model_reviewer_docs.v1',
  generatedAt: '2026-07-04T05:01:00.000Z',
  docsMode: 'local_readback_docs',
  query: {
    snapshotDate: '2026-07-04',
    evidenceWindow: { from: '2026-06-21', to: '2026-07-04', days: 14 },
    customerIds: ['1234567890'],
    productIds: ['P_SCALE'],
    maxAgeHours: { campaign_budgets: 24, product_performance: 24 },
    now: '2026-07-04T05:00:00.000Z',
  },
  safety: {
    read_only: true,
    dry_run: true,
    local_only: true,
    repository_read_only: true,
    read_model_query_used: true,
    foundation_snapshot_reused: true,
    source_review_export_reused: true,
    reviewer_export_readback: true,
    reviewer_docs_readback: true,
    reviewer_docs_persistence_performed: false,
    reviewer_export_persistence_performed: false,
    full_foundation_snapshot_payload_included: false,
    campaignBudgetId_fallback_used: false,
    provider_api_called: false,
    google_ads_api_called: false,
    validateOnly_called: false,
    live_ads_execution_used: false,
    erp_mutation_used: false,
    payment_mutation_used: false,
    order_mutation_used: false,
    inventory_mutation_used: false,
    execution_allowed_now: false,
    production_ready: false,
    provider_mutation_used: false,
    direct_google_ads_api_call: false,
    future_live_execution_allowed: false,
    live_path_implemented: false,
  },
  summary: {
    docs_status: 'needs_attention',
    docs_mode: 'local_readback_docs',
    source_export_mode: 'local_readback',
    source_export_schema_version: 'ads_automation_decision_foundation_read_model_review_export.v1',
    source_foundation_snapshot_schema_version: 'ads_automation_decision_foundation_snapshot.v1',
    read_model_source: 'mongo_read_model',
    rendered_sections: 5,
    attention_sections: 4,
    attention_section_ids: [
      'source_evidence',
      'query_evidence',
      'campaign_budget_join',
      'review_checklist',
    ],
    source_evidence_records_rendered: 6,
    stale_source_evidence_records: 1,
    missing_source_evidence_records: 0,
    missing_field_evidence_records: 1,
    query_evidence_records_rendered: 5,
    missing_query_evidence_records: 1,
    campaignBudgetId_required: true,
    campaignBudgetId_fallback_used: false,
    full_foundation_snapshot_payload_included: false,
    source_review_export_reused: true,
    reviewer_docs_persistence_performed: false,
    reviewer_export_persistence_performed: false,
    provider_api_called: false,
    google_ads_api_called: false,
    validateOnly_called: false,
    live_ads_execution_used: false,
    erp_mutation_used: false,
    payment_mutation_used: false,
    order_mutation_used: false,
    inventory_mutation_used: false,
    execution_allowed_now: false,
    production_ready: false,
    next_required_action: 'resolve_missing_read_model_evidence',
  },
  routeExamples: [
    {
      label: 'Foundation reviewer docs',
      method: 'POST',
      path: '/ai/ads-automation/decision-foundation-read-model-reviewer-docs',
      purpose: 'Render BA-facing foundation review sections without returning the full foundationSnapshot payload.',
      provider_api_called: false,
      erp_mutation_used: false,
    },
    {
      label: 'Foundation review export JSON',
      method: 'POST',
      path: '/ai/ads-automation/decision-foundation-read-model-review-export',
      purpose: 'Inspect the complete machine-readable foundation review export behind the docs view.',
      provider_api_called: false,
      erp_mutation_used: false,
    },
  ],
  renderedSections: [
    {
      section_id: 'safety_gates',
      title: 'Safety Gates',
      status: 'passed',
      lines: [
        'execution_allowed_now=false',
        'provider_api_called=false',
        'google_ads_api_called=false',
        'validateOnly_called=false',
        'live_ads_execution_used=false',
      ],
      evidence_record_ids: [],
    },
    {
      section_id: 'source_evidence',
      title: 'Source Evidence',
      status: 'attention',
      lines: [
        'campaign_budgets: stale, canUseForDecision=no, rows=1, latestObservedAt=2026-06-30T00:00:00.000Z, missingFields=none',
      ],
      evidence_record_ids: ['campaign_budgets'],
    },
    {
      section_id: 'query_evidence',
      title: 'Query Evidence',
      status: 'attention',
      lines: [
        'campaign_budgets/ad_group/2001: missing, rows=0, missingFields=campaignBudgetId_or_campaignBudgetResourceName, campaign budget evidence is required',
      ],
      evidence_record_ids: ['campaign_budgets:ad_group:2001'],
    },
    {
      section_id: 'campaign_budget_join',
      title: 'Campaign Budget Join',
      status: 'attention',
      lines: [
        'Missing campaignBudgetId_or_campaignBudgetResourceName for ad groups: 2001',
        'campaignBudgetId is required for budget drafts; campaignId/adGroupId are not fallback budget IDs.',
        'campaignBudgetId_fallback_used=false',
      ],
      evidence_record_ids: ['campaign_budgets:ad_group:2001'],
    },
    {
      section_id: 'review_checklist',
      title: 'Review Checklist',
      status: 'attention',
      lines: [
        'Resolve stale or missing source/query evidence before using this artifact for future approval review.',
        'Confirm campaignBudgetId is present for any future campaign budget draft; do not use campaignId or adGroupId as a fallback budget identifier.',
      ],
      evidence_record_ids: [],
    },
  ],
  markdownPreview: [
    '# Ads Automation Foundation Reviewer Docs',
    'Docs status: needs_attention',
    'Attention sections: source_evidence, query_evidence, campaign_budget_join, review_checklist',
    'Campaign budget fallback used: false',
    'Campaign budget rule: campaignBudgetId is required; campaignId/adGroupId are not fallback budget IDs.',
    'Full foundationSnapshot payload included: false',
    'Safety gates: execution_allowed_now=false, provider_api_called=false, google_ads_api_called=false, validateOnly_called=false, live_ads_execution_used=false',
  ].join('\n'),
  sourceExportDigest: {
    schemaVersion: 'ads_automation_decision_foundation_read_model_review_export.v1',
    generatedAt: '2026-07-04T05:00:30.000Z',
    exportMode: 'local_readback',
    review_export_route: '/ai/ads-automation/decision-foundation-read-model-review-export',
    foundation_snapshot_schema_version: 'ads_automation_decision_foundation_snapshot.v1',
    read_model_source: 'mongo_read_model',
    summary: { campaignBudgetId_fallback_used: false },
    rendered_section_ids: [
      'safety_gates',
      'source_evidence',
      'query_evidence',
      'campaign_budget_join',
      'review_checklist',
    ],
    evidence_record_ids: ['campaign_budgets:ad_group:2001'],
    omitted_payloads: ['foundationSnapshot'],
    full_foundation_snapshot_payload_included: false,
  },
};

export const ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE = {
  schemaVersion: 'ads_foundation_reviewer_docs_local_snapshot.v1',
  snapshotMode: 'local_browser_download',
  createdFromEndpoint: '/api/ai/ads-automation/decision-foundation-read-model-reviewer-docs',
  createdFromDocsGeneratedAt: ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.generatedAt,
  comparisonKey: [
    'ads_automation_decision_foundation_read_model_reviewer_docs.v1',
    'local_readback_docs',
    '2026-07-04T05:01:00.000Z',
    'needs_attention',
    '5',
    'source_evidence,query_evidence,campaign_budget_join,review_checklist',
    'provider_api_called=false',
    'google_ads_api_called=false',
    'validateOnly_called=false',
    'execution_allowed_now=false',
    'campaignBudgetId_fallback_used=false',
    'full_foundation_snapshot_payload_included=false',
  ].join('|'),
  docsSchemaVersion: ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.schemaVersion,
  docsMode: ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.docsMode,
  query: {
    snapshotDate: '2026-07-04',
    evidenceWindow: { from: '2026-06-21', to: '2026-07-04', days: 14 },
    customerIds: ['1234567890'],
    productIds: ['P_SCALE'],
    maxAgeHours: { campaign_budgets: 24, product_performance: 24 },
    now: '2026-07-04T05:00:00.000Z',
  },
  safety: {
    provider_api_called: false,
    google_ads_api_called: false,
    validateOnly_called: false,
    execution_allowed_now: false,
    production_ready: false,
    live_ads_execution_used: false,
    erp_mutation_used: false,
    payment_mutation_used: false,
    order_mutation_used: false,
    inventory_mutation_used: false,
    campaignBudgetId_fallback_used: false,
    full_foundation_snapshot_payload_included: false,
    reviewer_docs_persistence_performed: false,
    reviewer_export_persistence_performed: false,
  },
  summary: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.summary,
    attention_section_ids: [...ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.summary.attention_section_ids],
  },
  routeExamples: ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.routeExamples.map((example) => ({
    ...example,
  })),
  renderedSections: ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.renderedSections.map((section) => ({
    ...section,
    lines: [...section.lines],
    evidence_record_ids: [...section.evidence_record_ids],
  })),
  markdownPreview: ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.markdownPreview,
  sourceExportDigest: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.sourceExportDigest,
    summary: { ...ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.sourceExportDigest.summary },
    rendered_section_ids: [
      ...ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.sourceExportDigest.rendered_section_ids,
    ],
    evidence_record_ids: [
      ...ADS_FOUNDATION_REVIEWER_DOCS_LOCAL_FIXTURE.sourceExportDigest.evidence_record_ids,
    ],
    omitted_payloads: ['foundationSnapshot'],
  },
  omittedPayloads: ['foundationSnapshot'],
  provider_api_called: false,
  google_ads_api_called: false,
  validateOnly_called: false,
  execution_allowed_now: false,
  production_ready: false,
  campaignBudgetId_fallback_used: false,
  full_foundation_snapshot_payload_included: false,
} satisfies AdsFoundationReviewerDocsLocalSnapshot;

export const ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_A_FILE_FIXTURE = {
  ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE,
  createdFromDocsGeneratedAt: '2026-07-04T04:55:00.000Z',
  comparisonKey: [
    'ads_automation_decision_foundation_read_model_reviewer_docs.v1',
    'local_readback_docs',
    '2026-07-04T04:55:00.000Z',
    'needs_attention',
    '6',
    'source_evidence,query_evidence,campaign_budget_join,review_checklist,provider_safety',
    'provider_api_called=false',
    'google_ads_api_called=false',
    'validateOnly_called=false',
    'execution_allowed_now=false',
    'campaignBudgetId_fallback_used=false',
    'full_foundation_snapshot_payload_included=false',
  ].join('|'),
  summary: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.summary,
    rendered_sections: 6,
    attention_sections: 5,
    attention_section_ids: [
      ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.summary.attention_section_ids,
      'provider_safety',
    ],
    stale_source_evidence_records: 2,
    missing_query_evidence_records: 2,
    next_required_action: 'resolve_provider_safety_and_budget_evidence',
  },
  renderedSections: [
    ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.renderedSections,
    {
      section_id: 'provider_safety',
      title: 'Provider Safety',
      status: 'attention' as const,
      lines: [
        'provider_api_called=false; provider evidence stayed local but still needs BA sign-off before approval review.',
      ],
      evidence_record_ids: ['provider_safety'],
    },
  ],
  markdownPreview: [
    ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.markdownPreview,
    'Provider safety: local-only evidence file loaded for BA compare.',
  ].join('\n'),
  sourceExportDigest: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.sourceExportDigest,
    generatedAt: '2026-07-04T04:54:30.000Z',
    rendered_section_ids: [
      ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.sourceExportDigest.rendered_section_ids,
      'provider_safety',
    ],
    evidence_record_ids: [
      ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_B_FILE_FIXTURE.sourceExportDigest.evidence_record_ids,
      'provider_safety',
    ],
  },
} satisfies AdsFoundationReviewerDocsLocalSnapshot;

export const ADS_FOUNDATION_REVIEWER_DOCS_UNSAFE_SNAPSHOT_FILE_FIXTURE = {
  ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_A_FILE_FIXTURE,
  comparisonKey: 'baseline-unsafe-foundation-payload|local_readback_docs|2026-07-04T04:55:00.000Z',
  safety: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_A_FILE_FIXTURE.safety,
    provider_api_called: true,
    campaignBudgetId_fallback_used: true,
    full_foundation_snapshot_payload_included: true,
  },
  summary: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_A_FILE_FIXTURE.summary,
    campaignBudgetId_fallback_used: true,
    full_foundation_snapshot_payload_included: true,
  },
  sourceExportDigest: {
    ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_A_FILE_FIXTURE.sourceExportDigest,
    summary: {
      ...ADS_FOUNDATION_REVIEWER_DOCS_SNAPSHOT_A_FILE_FIXTURE.sourceExportDigest.summary,
      campaignBudgetId_fallback_used: true,
    },
    omitted_payloads: [] as unknown as ['foundationSnapshot'],
    full_foundation_snapshot_payload_included: true,
  },
  omittedPayloads: [] as unknown as ['foundationSnapshot'],
  provider_api_called: true,
  campaignBudgetId_fallback_used: true,
  full_foundation_snapshot_payload_included: true,
  foundationSnapshot: {
    redacted: false,
    fixturePurpose: 'local unsafe snapshot file regression only',
  },
};

export const ADS_FOUNDATION_REVIEWER_DOCS_EMPTY_SNAPSHOT_FILE_FIXTURE = '';

export const ADS_FOUNDATION_REVIEWER_DOCS_MALFORMED_SNAPSHOT_FILE_FIXTURE = [
  '{',
  '"schemaVersion":"ads_foundation_reviewer_docs_local_snapshot.v1",',
  '"snapshotMode":"local_browser_download"',
].join('');

export const ADS_FOUNDATION_REVIEWER_DOCS_WRONG_SCHEMA_SNAPSHOT_FILE_FIXTURE = {
  schemaVersion: 'ads_automation_decision_foundation_read_model_reviewer_docs.v1',
  snapshotMode: 'local_browser_download',
  generatedAt: '2026-07-04T05:01:00.000Z',
};

export const ADS_FOUNDATION_REVIEWER_DOCS_MISSING_COMPARE_FIELDS_SNAPSHOT_FILE_FIXTURE = {
  schemaVersion: 'ads_foundation_reviewer_docs_local_snapshot.v1',
  snapshotMode: 'local_browser_download',
  comparisonKey: 'local-invalid-missing-reviewer-docs-compare-fields',
};

export const ADS_FOUNDATION_REVIEWER_DOCS_COMPARE_FILE_FIXTURE = {
  schemaVersion: 'ads_foundation_reviewer_docs_local_snapshot_compare.v1',
  leftComparisonKey: 'baseline-unsafe-foundation-payload|local_readback_docs|2026-07-04T04:55:00.000Z',
  rightComparisonKey: [
    'ads_automation_decision_foundation_read_model_reviewer_docs.v1',
    'local_readback_docs',
    '2026-07-04T05:01:00.000Z',
    'needs_attention',
    '5',
    'source_evidence,query_evidence,campaign_budget_join,review_checklist',
    'provider_api_called=false',
    'google_ads_api_called=false',
    'validateOnly_called=false',
    'execution_allowed_now=false',
    'campaignBudgetId_fallback_used=false',
    'full_foundation_snapshot_payload_included=false',
  ].join('|'),
  sameComparisonKey: false,
  metricDeltas: [
    {
      key: 'attention_sections',
      label: 'Attention sections',
      leftValue: 5,
      rightValue: 4,
      delta: -1,
      changed: true,
    },
    {
      key: 'stale_source_evidence_records',
      label: 'Stale source evidence',
      leftValue: 2,
      rightValue: 1,
      delta: -1,
      changed: true,
    },
    {
      key: 'missing_source_evidence_records',
      label: 'Missing source evidence',
      leftValue: 0,
      rightValue: 0,
      delta: 0,
      changed: false,
    },
    {
      key: 'missing_field_evidence_records',
      label: 'Missing field evidence',
      leftValue: 1,
      rightValue: 1,
      delta: 0,
      changed: false,
    },
    {
      key: 'missing_query_evidence_records',
      label: 'Missing query evidence',
      leftValue: 2,
      rightValue: 1,
      delta: -1,
      changed: true,
    },
  ],
  safetyDeltas: [
    {
      key: 'provider_api_called',
      leftValue: true,
      rightValue: false,
      changed: true,
      rightGateClosed: true,
      rightGateOpen: false,
    },
    {
      key: 'full_foundation_snapshot_payload_included',
      leftValue: true,
      rightValue: false,
      changed: true,
      rightGateClosed: true,
      rightGateOpen: false,
    },
  ],
  attentionSectionDeltas: [
    {
      section_id: 'provider_safety',
      title: 'Provider Safety',
      leftPresent: true,
      rightPresent: false,
      leftStatus: 'attention',
      rightStatus: 'missing',
      changed: true,
    },
  ],
  campaignBudgetIdFallbackDelta: {
    key: 'campaignBudgetId_fallback_used',
    leftValue: false,
    rightValue: false,
    changed: false,
    rightGateClosed: true,
    rightGateOpen: false,
  },
  foundationSnapshotOmissionDelta: {
    leftOmitted: false,
    rightOmitted: true,
    changed: true,
  },
} satisfies AdsFoundationReviewerDocsLocalSnapshotCompareResult;

export const ADS_FOUNDATION_REVIEWER_DOCS_UNSAFE_COMPARE_FILE_FIXTURE = {
  ...ADS_FOUNDATION_REVIEWER_DOCS_COMPARE_FILE_FIXTURE,
  foundationSnapshot: { redacted: false },
};
