export const AI_DATA_PACK_GOOGLE_ADS_READONLY_ADAPTER = Symbol(
  "AI_DATA_PACK_GOOGLE_ADS_READONLY_ADAPTER",
);

export const GOOGLE_ADS_READONLY_SYNC_PORT = Symbol(
  "GOOGLE_ADS_READONLY_SYNC_PORT",
);

export const GOOGLE_ADS_READONLY_RAW_SYNC_PORT = Symbol(
  "GOOGLE_ADS_READONLY_RAW_SYNC_PORT",
);

export const GOOGLE_ADS_READONLY_ASSESSMENT_PORT = Symbol(
  "GOOGLE_ADS_READONLY_ASSESSMENT_PORT",
);

export const GOOGLE_ADS_READONLY_DISTRIBUTED_LOCK_PORT = Symbol(
  "GOOGLE_ADS_READONLY_DISTRIBUTED_LOCK_PORT",
);

export const GOOGLE_ADS_READONLY_AUDIT_PORT = Symbol(
  "GOOGLE_ADS_READONLY_AUDIT_PORT",
);

export const GOOGLE_ADS_READONLY_HTTP_CLIENT = Symbol(
  "GOOGLE_ADS_READONLY_HTTP_CLIENT",
);

export const GOOGLE_ADS_READONLY_POLICY_CONFIG = Symbol(
  "GOOGLE_ADS_READONLY_POLICY_CONFIG",
);

export const GOOGLE_ADS_READONLY_SYNC_EXECUTE_PERMISSION =
  "ai-data-pack.source-sync.google-ads.readonly.execute";

export const AI_DATA_PACK_SYNC_DETAIL_READ_PERMISSION =
  "ai-data-pack.export.sync-detail.read";
