import { AiOperatorScenarioContext } from "./ai-operator.interfaces";
import { removeVietnameseTone } from "./ai-operator.format";

export function enforceOperatorResponseContract(
  answer: string,
  scenarioContext: AiOperatorScenarioContext,
): string {
  const normalized = removeVietnameseTone(answer || "").toLowerCase();
  const hasDataSection =
    normalized.includes("du lieu") ||
    normalized.includes("source") ||
    normalized.includes("nguon");
  const hasRiskSection =
    normalized.includes("rui ro") ||
    normalized.includes("thieu du lieu") ||
    normalized.includes("missing");
  const hasApprovalSection =
    normalized.includes("can duyet") ||
    normalized.includes("phe duyet") ||
    normalized.includes("approval");
  if (hasDataSection && hasRiskSection && hasApprovalSection) return answer;

  const quality = scenarioContext.context?.assistantQuality || {};
  const loadedSources = Array.isArray(quality.loadedSources)
    ? quality.loadedSources
    : [];
  const dataGaps = Array.isArray(quality.dataGaps) ? quality.dataGaps : [];
  const notLoadedReadApis = Array.isArray(quality.notLoadedReadApis)
    ? quality.notLoadedReadApis
    : [];

  const addendum = [
    "",
    "Kiem tra chuan 9+:",
    `- Du lieu da doc: ${loadedSources.length ? loadedSources.slice(0, 8).join(", ") : "chua co source nao duoc load trong context hien tai"}.`,
    `- Do tin cay: ${quality.confidence || "unknown"}${typeof quality.score === "number" ? ` (${quality.score}/100)` : ""}.`,
    dataGaps.length || notLoadedReadApis.length
      ? `- Rui ro/thieu du lieu: ${[...dataGaps, ...notLoadedReadApis].slice(0, 8).join("; ")}.`
      : "- Rui ro/thieu du lieu: chua thay data gap lon trong context da cap.",
    "- Can duyet: moi hanh dong chi tien, thanh toan, rut tien, tang/giam ngan sach ads hoac thay doi provider deu can nguoi co tham quyen phe duyet.",
  ].join("\n");

  return `${answer.trim()}\n${addendum}`;
}

export function ensureVietnameseUiResponse(answer: string): string {
  const replacements: Array<[RegExp, string]> = [
    [/loaded:/g, "đã tải:"],
    [/loaded: none/g, "đã tải: chưa có"],
    [/financial dashboard/g, "bảng điều khiển tài chính"],
    [/forecast/g, "dự báo"],
    [/finance actions/g, "hành động tài chính"],
    [/ads performance/g, "hiệu suất quảng cáo"],
    [/ads suggestions/g, "gợi ý quảng cáo"],
    [/ads alerts/g, "cảnh báo quảng cáo"],
    [/ads sync health/g, "sức khỏe đồng bộ quảng cáo"],
    [/ads cost by ad group/g, "chi phí quảng cáo theo nhóm quảng cáo"],
    [/ads cost per order/g, "chi phí quảng cáo trên mỗi đơn"],
    [/\borders\b/g, "đơn hàng"],
    [/\breturns\b/g, "hàng hoàn"],
    [/\breceivables\b/g, "công nợ phải thu"],
    [/\boperations\b/g, "vận hành"],
    [/employee ads KPI/g, "KPI nhân viên quảng cáo"],
    [/ads token health/g, "sức khỏe token quảng cáo"],
    [/manager marketing context/g, "ngữ cảnh marketing của quản lý"],
    [/manager conversations/g, "hội thoại của quản lý"],
    [/manager pending orders/g, "đơn chờ xử lý của quản lý"],
    [/manager media context/g, "ngữ cảnh media của quản lý"],
    [/manager ad entities/g, "thực thể quảng cáo của quản lý"],
    [/funds overview/g, "tổng quan quỹ"],
    [/available funds/g, "vốn khả dụng"],
    [/budget preview/g, "xem trước ngân sách"],
    [/loan dashboard/g, "bảng khoản vay"],
    [/owner fund/g, "quỹ chủ sở hữu"],
    [/labor cashflow/g, "dòng tiền lương"],
    [/other cost cashflow/g, "dòng tiền chi phí khác"],
    [/ads cost cashflow/g, "dòng tiền chi phí quảng cáo"],
    [/ai marketing overview/g, "tổng quan AI marketing"],
    [/ai marketing plans/g, "kế hoạch AI marketing"],
    [/ai marketing evaluations/g, "đánh giá AI marketing"],
    [/quote readiness/g, "mức sẵn sàng báo giá"],
    [/access audit/g, "kiểm toán truy cập"],
    [/free cash/g, "tiền tự do"],
    [/committed cash/g, "tiền đã cam kết"],
    [/\bcommitted\b/g, "đã cam kết"],
    [/monthly burn/g, "mức đốt tiền hằng tháng"],
    [/\bdebt\b/g, "nợ"],
    [/\brunway\b/g, "thời gian chịu đựng"],
    [/owner withdrawable/g, "số tiền chủ sở hữu có thể rút"],
    [/available conservative/g, "vốn khả dụng thận trọng"],
    [/ads dry-run locked/g, "mô phỏng ngân sách quảng cáo đang khóa"],
    [/owner fund balance/g, "số dư quỹ chủ sở hữu"],
    [/\boutstanding\b/g, "chưa thanh toán"],
    [/\bstatement\b/g, "bảng kê"],
    [/\bsnapshot\b/g, "ảnh chụp dữ liệu"],
    [/\bscale ads\b/g, "tăng ngân sách quảng cáo"],
    [/allocation preview/g, "bản xem trước phân bổ"],
    [/\breserved\b/g, "đã giữ lại"],
    [/\bpayroll\b/g, "lương"],
    [/\bpayables\b/g, "khoản phải trả"],
    [/\bReadiness\b/g, "Mức sẵn sàng"],
    [/\breadiness\b/g, "mức sẵn sàng"],
    [/Needs human/g, "Cần người xử lý"],
    [/needs human/g, "cần người xử lý"],
    [/awaiting order/g, "đang chờ lên đơn"],
    [/pending order/g, "đơn chờ xử lý"],
    [/pending snapshot/g, "ảnh chụp dữ liệu đơn chờ xử lý"],
    [/\bmanager\b/g, "quản lý"],
    [/Token issues/g, "Vấn đề token"],
    [/token issues/g, "vấn đề token"],
    [/sync issues/g, "vấn đề đồng bộ"],
    [/sync health/g, "sức khỏe đồng bộ"],
    [/\bplatform\b/g, "nền tảng"],
    [/\bvalidate\b/g, "xác thực"],
    [/\binvalid\b/g, "không hợp lệ"],
    [/\bowner\b/g, "người phụ trách"],
    [/\bbulk assign\b/g, "phân công hàng loạt"],
    [/\bBulk assign\b/g, "Phân công hàng loạt"],
    [/\bbulk-assign\b/g, "phân công hàng loạt"],
    [/\bpause\b/g, "tạm dừng"],
    [/auto-AI/g, "AI tự động"],
    [/burn=0/g, "mức đốt tiền = 0"],
    [/\bScale\b/g, "tăng ngân sách"],
    [/\bscale\b/g, "tăng ngân sách"],
    [/\bads(?=\/|\s|,|\.|;|:|$)/g, "quảng cáo"],
    [/\bAds(?=\/|\s|,|\.|;|:|$)/g, "Quảng cáo"],
    [/\bcashflow\b/g, "dòng tiền"],
    [/\bdata gap\b/g, "khoảng trống dữ liệu"],
    [/\bbatch\b/g, "lô"],
    [/\bpenalty\b/g, "phạt"],
    [/Ket luan ngan/g, "Kết luận ngắn"],
    [/Du lieu da doc/g, "Dữ liệu đã đọc"],
    [/Phan tich tinh huong/g, "Phân tích tình huống"],
    [/Viec can lam/g, "Việc cần làm"],
    [/Rui ro\/thieu du lieu/g, "Rủi ro/thiếu dữ liệu"],
    [/Can duyet/g, "Cần duyệt"],
    [/Kiem tra chuan 9\+/g, "Kiểm tra chuẩn 9+"],
    [/Do tin cay/g, "Độ tin cậy"],
    [/Giam doc/g, "Giám đốc"],
    [/Ke toan/g, "Kế toán"],
    [/Quan ly/g, "Quản lý"],
    [/Tro ly/g, "Trợ lý"],
    [/Hien /g, "Hiện "],
    [/Hom nay/g, "Hôm nay"],
    [/chua /g, "chưa "],
    [/Chua /g, "Chưa "],
    [/du lieu/g, "dữ liệu"],
    [/Du lieu/g, "Dữ liệu"],
    [/nguon/g, "nguồn"],
    [/Nguon/g, "Nguồn"],
    [/khong/g, "không"],
    [/Khong/g, "Không"],
    [/co /g, "có "],
    [/Co /g, "Có "],
    [/can /g, "cần "],
    [/Can /g, "Cần "],
    [/duoc/g, "được"],
    [/Duoc/g, "Được"],
    [/doc/g, "đọc"],
    [/Doc/g, "Đọc"],
    [/tom tat/g, "tóm tắt"],
    [/Tom tat/g, "Tóm tắt"],
    [/hanh dong/g, "hành động"],
    [/Hanh dong/g, "Hành động"],
    [/thuc hien/g, "thực hiện"],
    [/Thuc hien/g, "Thực hiện"],
    [/phan tich/g, "phân tích"],
    [/Phan tich/g, "Phân tích"],
    [/de xuat/g, "đề xuất"],
    [/De xuat/g, "Đề xuất"],
    [/quyet dinh/g, "quyết định"],
    [/Quyet dinh/g, "Quyết định"],
    [/tai chinh/g, "tài chính"],
    [/Tai chinh/g, "Tài chính"],
    [/dong tien/g, "dòng tiền"],
    [/Dong tien/g, "Dòng tiền"],
    [/cong no/g, "công nợ"],
    [/Cong no/g, "Công nợ"],
    [/don/g, "đơn"],
    [/Don/g, "Đơn"],
    [/ngay/g, "ngày"],
    [/Ngay/g, "Ngày"],
    [/thang/g, "tháng"],
    [/Thang/g, "Tháng"],
    [/nhan vien/g, "nhân viên"],
    [/Nhan vien/g, "Nhân viên"],
    [/nha cung cap/g, "nhà cung cấp"],
    [/Nha cung cap/g, "Nhà cung cấp"],
    [/bat buoc/g, "bắt buộc"],
    [/Bat buoc/g, "Bắt buộc"],
    [/phe duyet/g, "phê duyệt"],
    [/Phe duyet/g, "Phê duyệt"],
    [/thieu/g, "thiếu"],
    [/Thieu/g, "Thiếu"],
    [/rui ro/g, "rủi ro"],
    [/Rui ro/g, "Rủi ro"],
    [/so tien/g, "số tiền"],
    [/So tien/g, "Số tiền"],
    [/pham vi/g, "phạm vi"],
    [/Pham vi/g, "Phạm vi"],
    [/nguoi/g, "người"],
    [/Nguoi/g, "Người"],
    [/goi y/g, "gợi ý"],
    [/Goi y/g, "Gợi ý"],
    [/kiem tra/g, "kiểm tra"],
    [/Kiem tra/g, "Kiểm tra"],
    [/theo doi/g, "theo dõi"],
    [/Theo doi/g, "Theo dõi"],
    [/hien tai/g, "hiện tại"],
    [/Hien tai/g, "Hiện tại"],
    [/he thong/g, "hệ thống"],
    [/He thong/g, "Hệ thống"],
    [/hoi thoai/g, "hội thoại"],
    [/Hoi thoai/g, "Hội thoại"],
    [/chat luong/g, "chất lượng"],
    [/Chat luong/g, "Chất lượng"],
    [/san xuat/g, "sản xuất"],
    [/San xuat/g, "Sản xuất"],
    [/giao hang/g, "giao hàng"],
    [/Giao hang/g, "Giao hàng"],
    [/khach/g, "khách"],
    [/Khach/g, "Khách"],
    [/hoa hong/g, "hoa hồng"],
    [/Hoa hong/g, "Hoa hồng"],
    [/bat thuong/g, "bất thường"],
    [/Bat thuong/g, "Bất thường"],
    [/\bnen\b/g, "nên"],
    [/\bNen\b/g, "Nên"],
    [/\btruoc\b/g, "trước"],
    [/\bTruoc\b/g, "Trước"],
    [/\bsau do\b/g, "sau đó"],
    [/\bSau do\b/g, "Sau đó"],
    [/\bmoi den\b/g, "mới đến"],
    [/\bMoi den\b/g, "Mới đến"],
    [/\bdiem tien thap nhat\b/g, "điểm tiền thấp nhất"],
    [/\bDiem tien thap nhat\b/g, "Điểm tiền thấp nhất"],
    [/\btai\b/g, "tại"],
    [/\bTai\b/g, "Tại"],
    [/\bno den han\b/g, "nợ đến hạn"],
    [/\bNo den han\b/g, "Nợ đến hạn"],
    [/\bco\b/g, "có"],
    [/\bCo\b/g, "Có"],
    [/\bva\b/g, "và"],
    [/\bVa\b/g, "Và"],
    [/\btang\b/g, "tăng"],
    [/\bTang\b/g, "Tăng"],
    [/\bgiam\b/g, "giảm"],
    [/\bGiam\b/g, "Giảm"],
    [/\bngan sach\b/g, "ngân sách"],
    [/\bNgan sach\b/g, "Ngân sách"],
    [/\brut\b/g, "rút"],
    [/\bRut\b/g, "Rút"],
    [/\btra no\b/g, "trả nợ"],
    [/\bTra no\b/g, "Trả nợ"],
    [/\btao\b/g, "tạo"],
    [/\bTao\b/g, "Tạo"],
    [/\bthanh toan\b/g, "thanh toán"],
    [/\bThanh toan\b/g, "Thanh toán"],
    [/\bthat\b/g, "thật"],
    [/\bThat\b/g, "Thật"],
    [/\bdeu\b/g, "đều"],
    [/\bDeu\b/g, "Đều"],
    [/\bxac nhan\b/g, "xác nhận"],
    [/\bXac nhan\b/g, "Xác nhận"],
    [/\bro\b/g, "rõ"],
    [/\bRo\b/g, "Rõ"],
    [/\bduyet\b/g, "duyệt"],
    [/\bDuyet\b/g, "Duyệt"],
    [/\bTam khoa\b/g, "Tạm khóa"],
    [/\btam khoa\b/g, "tạm khóa"],
    [/\bdieu kien\b/g, "điều kiện"],
    [/\bDieu kien\b/g, "Điều kiện"],
    [/\bdoi chieu\b/g, "đối chiếu"],
    [/\bDoi chieu\b/g, "Đối chiếu"],
    [/\blich\b/g, "lịch"],
    [/\bLich\b/g, "Lịch"],
    [/\bvoi\b/g, "với"],
    [/\bVoi\b/g, "Với"],
    [/\bquy\b/g, "quỹ"],
    [/\bQuy\b/g, "Quỹ"],
    [/\bchi hoac\b/g, "chi hoặc"],
    [/\bChi hoac\b/g, "Chi hoặc"],
    [/\bsoat\b/g, "soát"],
    [/\bSoat\b/g, "Soát"],
    [/\bluong\b/g, "lương"],
    [/\bLuong\b/g, "Lương"],
    [/\bcham cong\b/g, "chấm công"],
    [/\bCham cong\b/g, "Chấm công"],
    [/\bchung tu\b/g, "chứng từ"],
    [/\bChung tu\b/g, "Chứng từ"],
    [/\blich chi\b/g, "lịch chi"],
    [/\bLich chi\b/g, "Lịch chi"],
    [/\bchot\b/g, "chốt"],
    [/\bChot\b/g, "Chốt"],
    [/\bkhoan\b/g, "khoản"],
    [/\bKhoan\b/g, "Khoản"],
    [/\buu tien\b/g, "ưu tiên"],
    [/\bUu tien\b/g, "Ưu tiên"],
    [/\bcap nhat\b/g, "cập nhật"],
    [/\bCap nhat\b/g, "Cập nhật"],
    [/\bde\b/g, "để"],
    [/\bDe\b/g, "Để"],
    [/\btu\b/g, "từ"],
    [/\bTu\b/g, "Từ"],
    [/\bcac\b/g, "các"],
    [/\bCac\b/g, "Các"],
    [/\bcua\b/g, "của"],
    [/\bCua\b/g, "Của"],
    [/\btrong ky\b/g, "trong kỳ"],
    [/\bTrong ky\b/g, "Trong kỳ"],
    [/\bgan nhat\b/g, "gần nhất"],
    [/\bGan nhat\b/g, "Gần nhất"],
    [/\bkhuyen nghi\b/g, "khuyến nghị"],
    [/\bKhuyen nghi\b/g, "Khuyến nghị"],
    [/\ban toan\b/g, "an toàn"],
    [/\bAn toan\b/g, "An toàn"],
    [/\blon\b/g, "lớn"],
    [/\bLon\b/g, "Lớn"],
    [/\bbo sot\b/g, "bỏ sót"],
    [/\bBo sot\b/g, "Bỏ sót"],
    [/\bso dien thoai\b/g, "số điện thoại"],
    [/\bSo dien thoai\b/g, "Số điện thoại"],
    [/\bsan pham\b/g, "sản phẩm"],
    [/\bSan pham\b/g, "Sản phẩm"],
    [/\bgia\b/g, "giá"],
    [/\bGia\b/g, "Giá"],
    [/\bdoi\b/g, "đổi"],
    [/\bDoi\b/g, "Đổi"],
    [/\bCon (?=\d)/g, "Còn "],
    [/\bcon (?=\d)/g, "còn "],
    [/\bchi phi\b/g, "chi phí"],
    [/\bChi phi\b/g, "Chi phí"],
    [/ngân sách quảng cáo/g, "ngân sách quảng cáo"],
    [/ngân sách ads/g, "ngân sách quảng cáo"],
    [/Ngân sách ads/g, "Ngân sách quảng cáo"],
    [/quỹ chủ sở hữu balance/g, "số dư quỹ chủ sở hữu"],
    [/quỹ người phụ trách/g, "quỹ chủ sở hữu"],
    [/Rút người phụ trách/g, "Rút tiền chủ sở hữu"],
    [/rút người phụ trách/g, "rút tiền chủ sở hữu"],
    [/dự báo dòng tiền/g, "dự báo dòng tiền"],
    [/chi phí khac/g, "chi phí khác"],
    [/Chi phí khac/g, "Chi phí khác"],
    [/Von kha dung/g, "Vốn khả dụng"],
    [/von kha dung/g, "vốn khả dụng"],
    [/\bconservative\b/g, "thận trọng"],
    [/\bdang\b/g, "đang"],
    [/\bDang\b/g, "Đang"],
    [/\bthap\b/g, "thấp"],
    [/\bThap\b/g, "Thấp"],
    [/\bsan sang\b/g, "sẵn sàng"],
    [/\bSan sang\b/g, "Sẵn sàng"],
    [/quỹết/g, "quyết"],
    [/Quỹết/g, "Quyết"],
    [/quyết định sau/g, "quyết định sâu"],
    [/Quyết định sau/g, "Quyết định sâu"],
    [/can thiep/g, "can thiệp"],
    [/cần thiep/g, "cần can thiệp"],
    [/Can thiep/g, "Can thiệp"],
    [/Cần thiep/g, "Cần can thiệp"],
    [/cần quản lý cần can thiệp/g, "cần quản lý can thiệp"],
    [/Cần quản lý cần can thiệp/g, "Cần quản lý can thiệp"],
    [/cần quản lý cần thiệp/g, "cần quản lý can thiệp"],
    [/Cần quản lý cần thiệp/g, "Cần quản lý can thiệp"],
    [/\bsync\b/g, "đồng bộ"],
    [/\bSync\b/g, "Đồng bộ"],
    [/\bsocial\b/g, "mạng xã hội"],
    [/Rủi rõ/g, "Rủi ro"],
    [/rủi rõ/g, "rủi ro"],
    [/\bchi phi khac\b/g, "chi phí khác"],
    [/\bChi phi khac\b/g, "Chi phí khác"],
    [/\bvan hanh\b/g, "vận hành"],
    [/\bVan hanh\b/g, "Vận hành"],
    [/\bden han\b/g, "đến hạn"],
    [/\bDen han\b/g, "Đến hạn"],
    [/\bqua han\b/g, "quá hạn"],
    [/\bQua han\b/g, "Quá hạn"],
    [/\blech\b/g, "lệch"],
    [/\bLech\b/g, "Lệch"],
    [/\btat\b/g, "tắt"],
    [/\bTat\b/g, "Tắt"],
    [/\bthay\b/g, "thấy"],
    [/\bThay\b/g, "Thấy"],
    [/\btoi\b/g, "tới"],
    [/\bToi\b/g, "Tới"],
  ];

  return replacements.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    String(answer || "").trim(),
  );
}
