import { AdsPlatformSourceSyncStatusResponse } from './ads-platform-source-sync-status-reviewer.service';

export const ADS_PLATFORM_SOURCE_SYNC_STATUS_LOCAL_FIXTURE: AdsPlatformSourceSyncStatusResponse = {
  schemaVersion: 'ads_automation_platform_source_sync_status.v1',
  generatedAt: '2026-07-04T05:00:00.000Z',
  reportDate: '2026-07-04',
  safety: {
    read_only: true,
    dry_run: true,
    local_only: true,
    source_registry_reused: true,
    freshness_gate_reused: true,
    adapter_boundary_only: true,
    provider_api_called: false,
    google_ads_api_called: false,
    validateOnly_called: false,
    live_ads_execution_used: false,
    erp_mutation_used: false,
    payment_mutation_used: false,
    order_mutation_used: false,
    inventory_mutation_used: false,
    production_ready: false,
    execution_allowed_now: false,
    google_ads_production_enabled: false,
  },
  summary: {
    status: 'blocked',
    source_count: 3,
    ready_source_count: 1,
    blocked_source_count: 2,
    blocked_sources: ['google_ads', 'advertising_costs'],
    missing_config_sources: ['google_ads'],
    stale_sources: ['advertising_costs'],
    missing_coverage_sources: [],
    not_synced_sources: [],
    provider_api_called: false,
    google_ads_api_called: false,
    validateOnly_called: false,
    live_ads_execution_used: false,
    execution_allowed_now: false,
    production_ready: false,
    next_required_action: 'resolve_source_sync_blockers',
  },
  decisionGates: {
    canUseGoogleAdsDataClaim: false,
    canGenerateActionDraft: false,
    canRecommendAdsScale: false,
    canImportActionFile: false,
    canDryRun: false,
    canExecuteLive: false,
  },
  sources: [
    {
      sourceKey: 'google_ads',
      provider: 'google_ads',
      platform: 'google_ads',
      domain: 'ads',
      businessImportance: 'critical',
      status: 'missing_config',
      requiredConfigPresence: [
        {
          key: 'GOOGLE_ADS_DEVELOPER_TOKEN',
          required: true,
          present: true,
          acceptable: true,
          secret: true,
          value_exposed: false,
        },
        {
          key: 'GOOGLE_ADS_CLIENT_ID',
          required: true,
          present: true,
          acceptable: true,
          secret: true,
          value_exposed: false,
        },
        {
          key: 'GOOGLE_ADS_CLIENT_SECRET',
          required: true,
          present: false,
          acceptable: false,
          secret: true,
          value_exposed: false,
        },
        {
          key: 'GOOGLE_ADS_REFRESH_TOKEN',
          required: true,
          present: false,
          acceptable: false,
          secret: true,
          value_exposed: false,
        },
        {
          key: 'GOOGLE_ADS_CUSTOMER_ID',
          required: true,
          present: false,
          acceptable: false,
          secret: false,
          value_exposed: false,
        },
        {
          key: 'GOOGLE_ADS_PRODUCTION_ENABLED',
          required: false,
          present: false,
          acceptable: true,
          secret: false,
          value_exposed: false,
        },
      ],
      missingCredentialOrConfigBlockers: [
        'missing_config:GOOGLE_ADS_CLIENT_SECRET',
        'missing_config:GOOGLE_ADS_REFRESH_TOKEN',
        'missing_config:GOOGLE_ADS_CUSTOMER_ID',
      ],
      reportDateCoverage: {
        reportDate: '2026-07-04',
        coverageStatus: 'covered',
        reportDateRecordCount: 7,
        expectedRecordCount: null,
      },
      freshness: {
        freshnessStatus: 'fresh',
        maxStalenessMinutes: 60,
        freshnessMinutes: 15,
        staleByMinutes: 0,
        lastSuccessfulSyncAt: '2026-07-04T04:30:00.000Z',
        latestRecordUpdatedAt: '2026-07-04T04:45:00.000Z',
        latestRecordDate: '2026-07-04',
        latestSuccessfulSyncOrReadModelWatermark: '2026-07-04T04:30:00.000Z',
      },
      sourceSyncBlockers: [
        'missing_config:GOOGLE_ADS_CLIENT_SECRET',
        'missing_config:GOOGLE_ADS_REFRESH_TOKEN',
        'missing_config:GOOGLE_ADS_CUSTOMER_ID',
      ],
      warnings: [],
      canUseForAdsAutomationDecision: false,
      usableForAdsAutomationDecisions: false,
    },
    {
      sourceKey: 'advertising_costs',
      provider: 'erp_local',
      platform: 'erp_advertising_costs',
      domain: 'ads',
      businessImportance: 'critical',
      status: 'stale',
      requiredConfigPresence: [],
      missingCredentialOrConfigBlockers: [],
      reportDateCoverage: {
        reportDate: '2026-07-04',
        coverageStatus: 'covered',
        reportDateRecordCount: 7,
        expectedRecordCount: null,
      },
      freshness: {
        freshnessStatus: 'stale',
        maxStalenessMinutes: 60,
        freshnessMinutes: 240,
        staleByMinutes: 180,
        lastSuccessfulSyncAt: null,
        latestRecordUpdatedAt: '2026-07-04T01:00:00.000Z',
        latestRecordDate: '2026-07-04',
        latestSuccessfulSyncOrReadModelWatermark: '2026-07-04T01:00:00.000Z',
      },
      sourceSyncBlockers: ['freshness_stale'],
      warnings: ['advertising_costs watermark is older than the source registry max staleness'],
      canUseForAdsAutomationDecision: false,
      usableForAdsAutomationDecisions: false,
    },
    {
      sourceKey: 'product_mapping',
      provider: 'erp_local',
      platform: 'erp_product_mapping',
      domain: 'catalog',
      businessImportance: 'important',
      status: 'ready',
      requiredConfigPresence: [],
      missingCredentialOrConfigBlockers: [],
      reportDateCoverage: {
        reportDate: '2026-07-04',
        coverageStatus: 'not_applicable',
        reportDateRecordCount: null,
        expectedRecordCount: null,
      },
      freshness: {
        freshnessStatus: 'fresh',
        maxStalenessMinutes: 1440,
        freshnessMinutes: 30,
        staleByMinutes: 0,
        lastSuccessfulSyncAt: null,
        latestRecordUpdatedAt: '2026-07-04T04:20:00.000Z',
        latestRecordDate: null,
        latestSuccessfulSyncOrReadModelWatermark: '2026-07-04T04:20:00.000Z',
      },
      sourceSyncBlockers: [],
      warnings: [],
      canUseForAdsAutomationDecision: true,
      usableForAdsAutomationDecisions: true,
    },
  ],
};

export const ADS_PLATFORM_SOURCE_SYNC_STATUS_READY_LOCAL_FIXTURE: AdsPlatformSourceSyncStatusResponse = {
  ...ADS_PLATFORM_SOURCE_SYNC_STATUS_LOCAL_FIXTURE,
  generatedAt: '2026-07-04T06:00:00.000Z',
  safety: {
    ...ADS_PLATFORM_SOURCE_SYNC_STATUS_LOCAL_FIXTURE.safety,
  },
  summary: {
    ...ADS_PLATFORM_SOURCE_SYNC_STATUS_LOCAL_FIXTURE.summary,
    status: 'ready',
    ready_source_count: 3,
    blocked_source_count: 0,
    blocked_sources: [],
    missing_config_sources: [],
    stale_sources: [],
    missing_coverage_sources: [],
    not_synced_sources: [],
    next_required_action: 'ready_for_ads_automation_decision_review',
  },
  decisionGates: {
    ...ADS_PLATFORM_SOURCE_SYNC_STATUS_LOCAL_FIXTURE.decisionGates,
    canUseGoogleAdsDataClaim: true,
    canGenerateActionDraft: true,
    canRecommendAdsScale: true,
  },
  sources: ADS_PLATFORM_SOURCE_SYNC_STATUS_LOCAL_FIXTURE.sources.map((source) => {
    if (source.sourceKey === 'google_ads') {
      return {
        ...source,
        status: 'ready',
        requiredConfigPresence: source.requiredConfigPresence.map((item) => ({
          ...item,
          present: true,
          acceptable: true,
          value_exposed: false,
        })),
        missingCredentialOrConfigBlockers: [],
        sourceSyncBlockers: [],
        warnings: [],
        canUseForAdsAutomationDecision: true,
        usableForAdsAutomationDecisions: true,
      };
    }

    if (source.sourceKey === 'advertising_costs') {
      return {
        ...source,
        status: 'ready',
        freshness: {
          ...source.freshness,
          freshnessStatus: 'fresh',
          freshnessMinutes: 20,
          staleByMinutes: 0,
          latestRecordUpdatedAt: '2026-07-04T05:40:00.000Z',
          latestSuccessfulSyncOrReadModelWatermark: '2026-07-04T05:40:00.000Z',
        },
        sourceSyncBlockers: [],
        warnings: [],
        canUseForAdsAutomationDecision: true,
        usableForAdsAutomationDecisions: true,
      };
    }

    return {
      ...source,
      sourceSyncBlockers: [...source.sourceSyncBlockers],
      warnings: [...source.warnings],
    };
  }),
};
