import type {
  AdsAutomationReadonlyPlatformImportReadinessInput,
} from './contracts/ads-automation-readonly-platform-import-readiness.contract';

export const ADS_AUTOMATION_READONLY_PLATFORM_IMPORT_READINESS_FIXTURE:
  AdsAutomationReadonlyPlatformImportReadinessInput = {
    reportDate: '2026-07-04',
    now: '2026-07-04T05:00:00.000Z',
    fixtureMode: 'htx_ads_readiness_demo',
    accounts: [
      {
        platform: 'google_ads',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        loginCustomerId: '5555555555',
        accountName: 'HTX Bach Gia - Primary',
        isActive: true,
        approvedForReadOnlyImport: true,
        configuredForReadOnlyImport: true,
        googleAdsProductionEnabled: false,
        sourceTrustLevel: 'erp_local_verified',
        importWindow: {
          from: '2026-07-03',
          to: '2026-07-04',
          timezone: 'Asia/Bangkok',
          cadence: 'hourly',
          maxRangeDays: 31,
        },
        lastSuccessfulSyncAt: '2026-07-04T04:30:00.000Z',
        latestMetricDate: '2026-07-04',
        retryState: {
          status: 'idle',
          attempts: 0,
          maxAttempts: 3,
          nextRetryAt: null,
          backoffMs: null,
          lastFailureCategory: null,
        },
        freshnessMaxAgeMinutes: 90,
      },
      {
        platform: 'google_ads',
        accountId: 'HTX-GADS-SECONDARY',
        customerId: '2222222222',
        loginCustomerId: '5555555555',
        accountName: 'HTX Bach Gia - Secondary',
        isActive: true,
        approvedForReadOnlyImport: true,
        configuredForReadOnlyImport: true,
        googleAdsProductionEnabled: false,
        sourceTrustLevel: 'erp_local_verified',
        importWindow: {
          from: '2026-07-03',
          to: '2026-07-04',
          timezone: 'Asia/Bangkok',
          cadence: 'daily',
          maxRangeDays: 31,
        },
        lastSuccessfulSyncAt: '2026-07-03T02:00:00.000Z',
        latestMetricDate: '2026-07-03',
        failureReason: 'last_local_readonly_import_failed_rate_limited',
        retryState: {
          status: 'retry_scheduled',
          attempts: 1,
          maxAttempts: 3,
          nextRetryAt: '2026-07-04T06:00:00.000Z',
          backoffMs: 3600000,
          lastFailureCategory: 'rate_limited',
        },
        freshnessMaxAgeMinutes: 90,
      },
    ],
    metricRows: [
      {
        platform: 'google_ads',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1001',
        adGroupId: '2001',
        campaignBudgetId: '3001',
        date: '2026-07-04',
        spendVnd: 320000,
        clicks: 132,
        impressions: 6200,
        conversions: 13,
        conversionValueVnd: 4300000,
      },
      {
        platform: 'google_ads',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1002',
        adGroupId: '2002',
        campaignBudgetId: '3002',
        date: '2026-07-03',
        spendVnd: 210000,
        clicks: 94,
        impressions: 4100,
        conversions: 8,
        conversionValueVnd: 2500000,
      },
      {
        platform: 'google_ads',
        accountId: 'HTX-GADS-SECONDARY',
        customerId: '2222222222',
        campaignId: '9001',
        adGroupId: '9002',
        campaignBudgetId: null,
        date: '2026-07-03',
        spendVnd: 180000,
        clicks: 52,
        impressions: 1900,
        conversions: 2,
        conversionValueVnd: 600000,
      },
    ],
    decisionReadModel: {
      snapshotDate: '2026-07-04',
      evidenceWindow: { from: '2026-06-21', to: '2026-07-04', days: 14 },
      policy: {
        availableAdsCashVnd: 500000,
        cashflowGatePassed: true,
        maxBudgetIncreasePercent: 20,
        mediumConfidenceIncreasePercent: 10,
        minOrdersForScale: 5,
        minDataQualityScore: 0.75,
        minSpendForPauseVnd: 200000,
        maxReturnRatePercent: 25,
        minMarginPercent: 20,
        minStockAvailable: 10,
        minDaysOfCover: 7,
        maxSupplierLeadTimeDays: 10,
        maxSupplierLateDeliveryRatePercent: 15,
        maxSupplierReturnFaultRatePercent: 12,
        maxSupplierPaymentFreshnessDays: 30,
        lastSyncAt: '2026-07-04T04:30:00.000Z',
      },
      adGroups: [
        {
          platform: 'google_ads',
          accountId: '1234567890',
          customerId: '1234567890',
          campaignId: '1001',
          campaignName: 'HTX Search - Scale',
          adGroupId: '2001',
          adGroupName: 'Winning cookware ad group',
          resourceName: 'customers/1234567890/adGroups/2001',
          campaignBudgetId: '3001',
          campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
          currentStatus: 'ENABLED',
          currentBudgetVnd: 1000000,
          spendVnd: 320000,
          clicks: 132,
          impressions: 6200,
          conversions: 13,
          conversionValueVnd: 4300000,
          orders: 12,
          revenueVnd: 4300000,
          grossProfitVnd: 1720000,
          netProfitAfterAdsVnd: 760000,
          returnRatePercent: 8,
          dataQualityScore: 0.92,
          labels: [],
          productIds: ['P_SCALE'],
          bottlenecksChecked: true,
          lastSyncAt: '2026-07-04T04:30:00.000Z',
        },
        {
          platform: 'google_ads',
          accountId: '1234567890',
          customerId: '1234567890',
          campaignId: '1002',
          campaignName: 'HTX Search - Pause Review',
          adGroupId: '2002',
          adGroupName: 'Refund-heavy cookware ad group',
          resourceName: 'customers/1234567890/adGroups/2002',
          campaignBudgetId: '3002',
          campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3002',
          currentStatus: 'ENABLED',
          currentBudgetVnd: 500000,
          spendVnd: 350000,
          clicks: 88,
          impressions: 4100,
          conversions: 0,
          conversionValueVnd: 0,
          orders: 0,
          revenueVnd: 0,
          grossProfitVnd: 0,
          netProfitAfterAdsVnd: -350000,
          returnRatePercent: 40,
          dataQualityScore: 0.88,
          labels: [],
          productIds: ['P_BAD'],
          bottlenecksChecked: true,
          lastSyncAt: '2026-07-04T04:30:00.000Z',
        },
      ],
      products: [
        {
          productId: 'P_SCALE',
          sku: 'SKU-SCALE',
          productName: 'Profitable cooker set',
          netProfitVnd: 1250000,
          adAttributedNetProfitAfterAdsVnd: 760000,
          marginPercent: 45,
          returnCancelRefundRatePercent: 8,
          stockAvailable: 120,
          reservedQuantity: 10,
          incomingQuantity: 40,
          daysOfCover: 20,
          mediaReady: true,
          landingReady: true,
          offerReady: true,
          mappedAdGroupIds: ['2001'],
          supplierIds: ['SUP_SAFE'],
          updatedAt: '2026-07-04T04:30:00.000Z',
        },
        {
          productId: 'P_BAD',
          sku: 'SKU-BAD',
          productName: 'Refund-heavy set',
          netProfitVnd: -450000,
          adAttributedNetProfitAfterAdsVnd: -350000,
          marginPercent: -5,
          returnCancelRefundRatePercent: 40,
          stockAvailable: 50,
          reservedQuantity: 5,
          incomingQuantity: 0,
          daysOfCover: 12,
          mediaReady: true,
          landingReady: true,
          offerReady: true,
          mappedAdGroupIds: ['2002'],
          supplierIds: ['SUP_WEAK_1', 'SUP_WEAK_2'],
          updatedAt: '2026-07-04T04:30:00.000Z',
        },
      ],
      suppliers: [
        {
          productId: 'P_SCALE',
          supplierId: 'SUP_SAFE',
          supplierName: 'Safe Supplier',
          quoteApproved: true,
          currentQuoteVnd: 180000,
          priorQuoteVnd: 185000,
          marginAfterCostPercent: 42,
          leadTimeDays: 4,
          lateDeliveryRatePercent: 3,
          paymentFreshnessDays: 5,
          capacityStatus: 'available',
          returnFaultRatePercent: 2,
          updatedAt: '2026-07-04T04:30:00.000Z',
        },
        {
          productId: 'P_BAD',
          supplierId: 'SUP_WEAK_1',
          supplierName: 'Weak Supplier 1',
          quoteApproved: true,
          currentQuoteVnd: 260000,
          priorQuoteVnd: 230000,
          marginAfterCostPercent: 8,
          leadTimeDays: 14,
          lateDeliveryRatePercent: 20,
          paymentFreshnessDays: 45,
          capacityStatus: 'constrained',
          returnFaultRatePercent: 14,
          updatedAt: '2026-07-04T04:30:00.000Z',
        },
        {
          productId: 'P_BAD',
          supplierId: 'SUP_WEAK_2',
          supplierName: 'Weak Supplier 2',
          quoteApproved: false,
          currentQuoteVnd: 280000,
          priorQuoteVnd: 250000,
          marginAfterCostPercent: -2,
          leadTimeDays: 16,
          lateDeliveryRatePercent: 22,
          paymentFreshnessDays: 60,
          capacityStatus: 'blocked',
          returnFaultRatePercent: 18,
          updatedAt: '2026-07-04T04:30:00.000Z',
        },
      ],
    },
    decisionSafety: {
      grossMarginSafe: true,
      contributionProfitPositive: true,
      cashConversionWorkingCapitalSafe: false,
      stockCoverageSafe: true,
      supplierReliabilitySafe: false,
      fulfillmentCapacitySafe: false,
      returnRefundRiskSafe: true,
      dataFreshnessSafe: false,
      dailyLossLimitSafe: false,
      monthlyLossLimitSafe: false,
    },
  };
