import type { AdsAutomationApprovalPreflightReviewExportInput } from "./contracts/ads-automation-approval-preflight-review-export.contract";
import type { AdsAutomationExecutionPreflightGateFamilyKey } from "./contracts/ads-automation-execution-preflight-dry-run.contract";

const REPORT_DATE = "2026-07-04";
const GENERATED_AT = "2026-07-04T08:00:00.000Z";
const SCALE_APPROVAL_ID =
  "ADSAPPROVAL-approval-preflight-demo-scale-missing-budget";
const PAUSE_APPROVAL_ID = "ADSAPPROVAL-approval-preflight-demo-pause-campaign";
const EXECUTION_READINESS_GATE_FAMILIES: AdsAutomationExecutionPreflightGateFamilyKey[] =
  [
    "future_execution_action_scope",
    "approval_status",
    "approval_decision_audit",
    "source_readiness",
    "validateOnly",
    "finance_policy",
    "kill_switch",
    "idempotency",
    "production_flag",
    "provider_identifiers",
    "live_path",
  ];
const EXECUTION_READINESS_MUST_HAVE_BEFORE_FUTURE_LIVE = [
  "approved_action_present",
  "approval_decision_audit_persisted",
  "source_readiness_safe",
  "validateOnly_status_passed",
  "finance_policy_allowed",
  "kill_switch_off",
  "safe_idempotency_key",
  "campaignBudgetId_present_for_update_campaign_budget",
  "preflight_dry_run_record_persisted",
  "GOOGLE_ADS_PRODUCTION_ENABLED_true",
  "live_executor_path_implemented_later",
];

const staleSourceEvidence = [
  {
    sourceKey: "google_ads",
    reportDate: REPORT_DATE,
    freshnessStatus: "fresh",
    coverageStatus: "covered",
    lastSuccessfulSyncAt: "2026-07-04T06:45:00.000Z",
    latestRecordDate: REPORT_DATE,
    blockingReason: null,
    blockingReasons: [],
    canUseForAdsAutomationDecision: true,
  },
  {
    sourceKey: "advertising_costs",
    reportDate: REPORT_DATE,
    freshnessStatus: "stale",
    coverageStatus: "covered",
    lastSuccessfulSyncAt: "2026-07-02T06:45:00.000Z",
    latestRecordDate: REPORT_DATE,
    blockingReason: "freshness_stale",
    blockingReasons: [
      "advertising_costs_not_ready_for_ads_automation_decision",
      "freshness_stale",
    ],
    canUseForAdsAutomationDecision: false,
  },
  {
    sourceKey: "supplier_safety",
    reportDate: REPORT_DATE,
    freshnessStatus: "missing",
    coverageStatus: "missing",
    lastSuccessfulSyncAt: null,
    latestRecordDate: null,
    blockingReason: "coverage_missing",
    blockingReasons: [
      "supplier_safety_not_ready_for_ads_automation_decision",
      "coverage_missing",
    ],
    canUseForAdsAutomationDecision: false,
  },
];

const freshSourceEvidence = staleSourceEvidence.map((evidence) => ({
  ...evidence,
  freshnessStatus: evidence.sourceKey === "supplier_safety" ? "fresh" : "fresh",
  coverageStatus:
    evidence.sourceKey === "supplier_safety"
      ? "covered"
      : evidence.coverageStatus,
  lastSuccessfulSyncAt: "2026-07-04T06:45:00.000Z",
  latestRecordDate: REPORT_DATE,
  blockingReason: null,
  blockingReasons: [],
  canUseForAdsAutomationDecision: true,
}));

const scaleApproval = {
  approval_id: SCALE_APPROVAL_ID,
  source_schema_version: "ads_automation_decision_draft_preview.v1",
  source_draft_id: "ADSDRAFT-approval-preflight-demo-scale-missing-budget",
  source_decision_id: "DEC-scale-approval-preflight-demo-2001",
  action_type: "update_campaign_budget",
  action_family: "provider_google_ads",
  provider: "google",
  resource_type: "campaign_budget",
  entity_type: "ad_group",
  entity_id: "2001",
  accountId: "1234567890",
  productId: "P_SCALE_BLOCKED",
  supplierId: "SUP_STALE",
  platform: "google",
  status: "pending_approval",
  approval_required: true,
  execution_allowed_now: false,
  validate_only_required: true,
  future_provider_validateOnly_required: true,
  provider_api_called: false,
  google_ads_api_called: false,
  live_ads_execution_used: false,
  erp_mutation_used: false,
  payment_mutation_used: false,
  persistence_used: true,
  durable_storage_used: true,
  erp_local_persistence_used: true,
  provider_persistence_used: false,
  storage: "erp_local_mongo",
  typedPayload: {
    customerId: "1234567890",
    campaignId: "1001",
    adGroupId: "2001",
    campaignBudgetId: null,
    campaignBudgetResourceName: null,
    dailyBudget: 1200000,
    currentBudgetVnd: 1000000,
    increasePercent: 20,
  },
  source_evidence_references: [
    {
      decision_id: "DEC-scale-approval-preflight-demo-2001",
      decision_type: "scale_amount",
      evidence_window: { from: "2026-06-21", to: REPORT_DATE, days: 14 },
      evidence_metrics: {
        grossMarginVnd: null,
        contributionProfitVnd: null,
        netProfitAfterAdsVnd: null,
      },
      rationale:
        "Scale was suggested but must stay blocked until ERP source, finance, validateOnly, approval, audit, and preflight gates are complete.",
      idempotency_key: "ads-decision:2026-07-04:scale:2001",
      rollback_plan:
        "Restore previous campaign budget from ERP synced read model before any future live attempt.",
    },
  ],
  sourceSyncDecisionEvidence: staleSourceEvidence,
  sourceSyncDecisionGates: {
    canGenerateActionDraft: false,
    canRecommendAdsScale: false,
    canUseGoogleAdsDataClaim: false,
  },
  blockers: ["gross_margin_missing", "contribution_profit_missing"],
  missing_data_blockers: [
    "daily_loss_limit_missing",
    "campaignBudgetId_missing_no_fallback",
  ],
  idempotency_key: "ads draft unsafe whitespace",
  rationale: "Blocked local scale candidate for gate-family regression.",
  createdAt: "2026-07-04T07:00:00.000Z",
  persistedAt: "2026-07-04T07:00:00.000Z",
};

const pauseApproval = {
  approval_id: PAUSE_APPROVAL_ID,
  source_schema_version: "ads_automation_decision_draft_preview.v1",
  source_draft_id: "ADSDRAFT-approval-preflight-demo-pause-campaign",
  source_decision_id: "DEC-pause-approval-preflight-demo-1001",
  action_type: "pause_campaign",
  action_family: "provider_google_ads",
  provider: "google",
  resource_type: "campaign",
  entity_type: "campaign",
  entity_id: "1001",
  accountId: "1234567890",
  productId: "P_LOSS_LIMIT",
  supplierId: null,
  platform: "google",
  status: "approved",
  approval_required: true,
  execution_allowed_now: false,
  validate_only_required: true,
  future_provider_validateOnly_required: true,
  provider_api_called: false,
  google_ads_api_called: false,
  live_ads_execution_used: false,
  erp_mutation_used: false,
  payment_mutation_used: false,
  persistence_used: true,
  durable_storage_used: true,
  erp_local_persistence_used: true,
  provider_persistence_used: false,
  storage: "erp_local_mongo",
  typedPayload: {
    customerId: "1234567890",
    campaignId: "1001",
    targetStatus: "PAUSED",
    reason: "Daily loss limit exceeded in ERP review.",
  },
  source_evidence_references: [
    {
      decision_id: "DEC-pause-approval-preflight-demo-1001",
      decision_type: "campaign_or_ad_group_pause",
      evidence_window: { from: "2026-06-21", to: REPORT_DATE, days: 14 },
      evidence_metrics: { netProfitAfterAdsVnd: -900000, spendVnd: 2500000 },
      rationale: "Pause campaign remains visible as a safety action.",
      idempotency_key: "ads-decision:2026-07-04:pause:1001",
      rollback_plan:
        "Human can re-enable campaign only after ERP loss review clears.",
    },
  ],
  sourceSyncDecisionEvidence: freshSourceEvidence,
  sourceSyncDecisionGates: {
    canGenerateActionDraft: true,
    canRecommendAdsScale: false,
    canUseGoogleAdsDataClaim: true,
  },
  blockers: [],
  missing_data_blockers: [],
  idempotency_key: "ads-draft:2026-07-04:pause_campaign:1001",
  rationale: "Pause action approved locally after ERP evidence review.",
  createdAt: "2026-07-04T07:05:00.000Z",
  persistedAt: "2026-07-04T07:05:00.000Z",
};

export const ADS_AUTOMATION_APPROVAL_PREFLIGHT_REVIEW_EXPORT_FIXTURE = {
  reportDate: REPORT_DATE,
  now: GENERATED_AT,
  exportMode: "local_demo_fixture",
  fixtureName: "htx_ads_approval_preflight_review_demo",
  sourceReadinessReviewExport: {
    schemaVersion: "ads_automation_source_readiness_review_export.v1",
    generatedAt: "2026-07-04T07:30:00.000Z",
    exportMode: "local_demo_fixture",
    query: {
      reportDate: REPORT_DATE,
      fixture: "htx_ads_source_readiness_review_demo",
    },
    safety: {
      read_only: true,
      dry_run: true,
      local_only: true,
      report_only: true,
      fixture_or_payload_only: true,
      source_sync_status_reused: true,
      readonly_import_readiness_reused: true,
      decision_read_model_evidence_reused: true,
      repository_write_used: false,
      persistence_used: false,
      provider_api_called: false,
      provider_api_used: false,
      google_ads_api_called: false,
      google_ads_api_used: false,
      validateOnly_called: false,
      validate_only_provider_call_used: false,
      live_ads_execution_used: false,
      erp_mutation_used: false,
      payment_mutation_used: false,
      order_mutation_used: false,
      inventory_mutation_used: false,
      campaignBudgetId_required: true,
      campaignBudgetId_no_fallback: true,
      campaignBudgetId_fallback_used: false,
      GOOGLE_ADS_PRODUCTION_ENABLED: false,
      future_live_execution_allowed: false,
      execution_allowed_now: false,
      production_ready: false,
    },
    summary: {
      export_status: "needs_attention",
      export_mode: "local_demo_fixture",
      reportDate: REPORT_DATE,
      source_sync_status: "blocked",
      readonly_import_status: "blocked",
      source_count: 5,
      fresh_source_count: 2,
      stale_source_count: 2,
      missing_source_count: 1,
      blocked_source_count: 3,
      latest_successful_sync_at: "2026-07-04T06:45:00.000Z",
      latest_record_date: REPORT_DATE,
      total_spend_vnd: 5200000,
      total_clicks: 420,
      total_impressions: 18000,
      total_conversions: 18,
      total_conversion_value_vnd: 9800000,
      platform_metric_row_count: 3,
      platform_metric_ready_row_count: 2,
      platform_campaign_count: 2,
      platform_ad_group_count: 2,
      platform_campaignBudget_count: 1,
      platform_campaignBudgetId_missing_rows: 1,
      platform_mapped_product_count: 1,
      platform_mapped_ad_group_count: 1,
      platform_unmapped_ad_group_count: 1,
      platform_profitable_product_count: 0,
      platform_blocked_product_count: 2,
      platform_safe_supplier_count: 0,
      platform_blocked_supplier_count: 2,
      platform_supplier_choice_safe: false,
      platform_latest_successful_sync_at: "2026-07-04T06:45:00.000Z",
      platform_latest_record_date: REPORT_DATE,
      platform_entity_blocking_reason_count: 13,
      campaignBudgetId_missing_rows: 1,
      campaignBudgetId_required: true,
      campaignBudgetId_no_fallback: true,
      campaignBudgetId_fallback_used: false,
      scale_up_candidate_count: 1,
      scale_up_candidates_blocked: 1,
      pause_candidate_count: 1,
      product_kill_candidate_count: 0,
      product_allocation_blocker_count: 1,
      supplier_safety_blocker_count: 1,
      cashflow_first_scale_mode: "monitor_only",
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      execution_allowed_now: false,
      production_ready: false,
      next_required_action: "resolve_source_readiness_blockers",
    },
    platformEntityCoverage: {
      metrics: {
        rows: 3,
        readyRows: 2,
        spendVnd: 5200000,
        costVnd: 5200000,
        clicks: 420,
        impressions: 18000,
        conversions: 18,
        conversionValueVnd: 9800000,
      },
      campaigns: {
        campaignIds: ["1001", "1002"],
        readModelCampaignIds: ["1001", "1002"],
        missingReadModelCampaignIds: [],
        coveredCampaignCount: 2,
        missingCampaignIdRows: 1,
        metricRollups: [
          {
            entityId: "1001",
            accountIds: ["1234567890"],
            customerIds: ["1234567890"],
            campaignIds: ["1001"],
            adGroupIds: ["2001"],
            campaignBudgetIds: [],
            mappedProductIds: ["P_SCALE_BLOCKED"],
            supplierIds: ["SUP_STALE"],
            dates: [REPORT_DATE],
            reportDateCovered: true,
            rows: 1,
            readyRows: 0,
            spendVnd: 3200000,
            costVnd: 3200000,
            clicks: 260,
            impressions: 11000,
            conversions: 12,
            conversionValueVnd: 6000000,
            linkedDecisionTypes: ["scale_amount"],
            linkedDecisionEffectiveStatuses: ["blocked"],
            blockers: ["campaignBudgetId_missing_no_fallback"],
            coveredForDecision: false,
          },
          {
            entityId: "1002",
            accountIds: ["1234567890"],
            customerIds: ["1234567890"],
            campaignIds: ["1002"],
            adGroupIds: ["2002"],
            campaignBudgetIds: ["3002"],
            mappedProductIds: ["P_BAD"],
            supplierIds: ["SUP_WEAK_1"],
            dates: [REPORT_DATE],
            reportDateCovered: true,
            rows: 1,
            readyRows: 1,
            spendVnd: 2000000,
            costVnd: 2000000,
            clicks: 160,
            impressions: 7000,
            conversions: 0,
            conversionValueVnd: 0,
            linkedDecisionTypes: ["campaign_or_ad_group_pause"],
            linkedDecisionEffectiveStatuses: ["blocked"],
            blockers: ["negative_product_economics"],
            coveredForDecision: false,
          },
        ],
        blockers: ["campaignId_missing_rows"],
        coveredForDecision: false,
      },
      adGroups: {
        adGroupIds: ["2001", "2002"],
        readModelAdGroupIds: ["2001", "2002"],
        missingReadModelAdGroupIds: [],
        coveredAdGroupCount: 2,
        missingAdGroupIdRows: 1,
        metricRollups: [
          {
            entityId: "2001",
            accountIds: ["1234567890"],
            customerIds: ["1234567890"],
            campaignIds: ["1001"],
            adGroupIds: ["2001"],
            campaignBudgetIds: [],
            mappedProductIds: ["P_SCALE_BLOCKED"],
            supplierIds: ["SUP_STALE"],
            dates: [REPORT_DATE],
            reportDateCovered: true,
            rows: 1,
            readyRows: 0,
            spendVnd: 3200000,
            costVnd: 3200000,
            clicks: 260,
            impressions: 11000,
            conversions: 12,
            conversionValueVnd: 6000000,
            linkedDecisionTypes: ["scale_amount"],
            linkedDecisionEffectiveStatuses: ["blocked"],
            blockers: ["campaignBudgetId_missing_no_fallback"],
            coveredForDecision: false,
          },
          {
            entityId: "2002",
            accountIds: ["1234567890"],
            customerIds: ["1234567890"],
            campaignIds: ["1002"],
            adGroupIds: ["2002"],
            campaignBudgetIds: ["3002"],
            mappedProductIds: ["P_BAD"],
            supplierIds: ["SUP_WEAK_1"],
            dates: [REPORT_DATE],
            reportDateCovered: true,
            rows: 1,
            readyRows: 1,
            spendVnd: 2000000,
            costVnd: 2000000,
            clicks: 160,
            impressions: 7000,
            conversions: 0,
            conversionValueVnd: 0,
            linkedDecisionTypes: ["campaign_or_ad_group_pause"],
            linkedDecisionEffectiveStatuses: ["blocked"],
            blockers: ["negative_product_economics"],
            coveredForDecision: false,
          },
        ],
        blockers: ["adGroupId_missing_rows"],
        coveredForDecision: false,
      },
      campaignBudgets: {
        campaignBudgetIds: ["3002"],
        readModelCampaignBudgetIds: ["3002"],
        missingReadModelCampaignBudgetIds: [],
        coveredCampaignBudgetCount: 1,
        missingCampaignBudgetIdRows: 1,
        campaignBudgetId_required: true,
        campaignBudgetId_no_fallback: true,
        campaignBudgetId_fallback_used: false,
        metricRollups: [
          {
            entityId: "3002",
            accountIds: ["1234567890"],
            customerIds: ["1234567890"],
            campaignIds: ["1002"],
            adGroupIds: ["2002"],
            campaignBudgetIds: ["3002"],
            mappedProductIds: ["P_BAD"],
            supplierIds: ["SUP_WEAK_1"],
            dates: [REPORT_DATE],
            reportDateCovered: true,
            rows: 1,
            readyRows: 1,
            spendVnd: 2000000,
            costVnd: 2000000,
            clicks: 160,
            impressions: 7000,
            conversions: 0,
            conversionValueVnd: 0,
            linkedDecisionTypes: ["campaign_or_ad_group_pause"],
            linkedDecisionEffectiveStatuses: ["blocked"],
            blockers: ["negative_product_economics"],
            coveredForDecision: false,
          },
        ],
        blockers: ["campaignBudgetId_missing_no_fallback"],
        coveredForDecision: false,
      },
      productMapping: {
        mappedProductIds: ["P_BAD"],
        mappedAdGroupIds: ["2002"],
        unmappedAdGroupIds: ["2001"],
        sourceReady: false,
        productMappings: [
          {
            productId: "P_BAD",
            mappedAdGroupIds: ["2002"],
            campaignBudgetIds: ["3002"],
            supplierIds: ["SUP_WEAK_1"],
            blockers: ["product_budget_allocation_blocked_by_negative_margin"],
            coveredForDecision: false,
          },
          {
            productId: "P_SCALE_BLOCKED",
            mappedAdGroupIds: [],
            campaignBudgetIds: [],
            supplierIds: ["SUP_STALE"],
            blockers: ["product_mapping_unmapped_ad_groups"],
            coveredForDecision: false,
          },
        ],
        blockers: ["product_mapping_unmapped_ad_groups"],
        coveredForDecision: false,
      },
      inventoryProfit: {
        profitableProductIds: [],
        blockedProductIds: ["P_BAD", "P_SCALE_BLOCKED"],
        missingMappedProductIds: [],
        sourceReady: false,
        productReadiness: [
          {
            productId: "P_BAD",
            netProfitVnd: -450000,
            adAttributedNetProfitAfterAdsVnd: -350000,
            marginPercent: -5,
            stockAvailable: 50,
            daysOfCover: 12,
            canReceiveBudget: false,
            needsKillOrStopReview: true,
            blockers: [
              "product_net_profit_not_positive",
              "negative_product_economics",
            ],
            coveredForDecision: false,
          },
          {
            productId: "P_SCALE_BLOCKED",
            netProfitVnd: null,
            adAttributedNetProfitAfterAdsVnd: null,
            marginPercent: null,
            stockAvailable: null,
            daysOfCover: null,
            canReceiveBudget: false,
            needsKillOrStopReview: false,
            blockers: [
              "inventory_profit_not_ready_for_ads_automation_decision",
            ],
            coveredForDecision: false,
          },
        ],
        blockers: ["inventory_profit_not_ready_for_ads_automation_decision"],
        coveredForDecision: false,
      },
      supplierContext: {
        safeSupplierIds: [],
        blockedSupplierIds: ["SUP_STALE", "SUP_WEAK_1"],
        missingMappedSupplierIds: [],
        supplierChoiceSafe: false,
        sourceReady: false,
        supplierReadiness: [
          {
            supplierId: "SUP_WEAK_1",
            productId: "P_BAD",
            quoteApproved: true,
            marginAfterCostPercent: 8,
            leadTimeDays: 14,
            lateDeliveryRatePercent: 20,
            paymentFreshnessDays: 45,
            capacityStatus: "constrained",
            returnFaultRatePercent: 14,
            safeForBudgetAllocation: false,
            blockers: [
              "supplier_safety_not_ready_for_ads_automation_decision",
              "supplier_lead_time_too_high",
            ],
            coveredForDecision: false,
          },
          {
            supplierId: "SUP_STALE",
            productId: "P_SCALE_BLOCKED",
            quoteApproved: null,
            marginAfterCostPercent: null,
            leadTimeDays: null,
            lateDeliveryRatePercent: null,
            paymentFreshnessDays: null,
            capacityStatus: null,
            returnFaultRatePercent: null,
            safeForBudgetAllocation: false,
            blockers: ["supplier_safety_not_ready_for_ads_automation_decision"],
            coveredForDecision: false,
          },
        ],
        blockers: ["supplier_safety_not_ready_for_ads_automation_decision"],
        coveredForDecision: false,
      },
      freshnessCoverage: {
        latestSuccessfulSyncAt: "2026-07-04T06:45:00.000Z",
        latestRecordDate: REPORT_DATE,
        blockingReasons: ["freshness_stale"],
      },
    },
    blockerReview: {
      sourceBlockers: [
        "advertising_costs_not_ready_for_ads_automation_decision",
        "supplier_safety_not_ready_for_ads_automation_decision",
      ],
      readonlyImportBlockers: ["readonly_import_blocked_by_stale_sources"],
      readModelBlockers: ["gross_margin_missing"],
      productAllocationBlockers: [
        "inventory_profit_not_ready_for_ads_automation_decision",
      ],
      supplierSafetyBlockers: [
        "supplier_safety_not_ready_for_ads_automation_decision",
      ],
      cashflowFirstBlockers: ["cashflow_first_scale_mode_monitor_only"],
      globalBlockers: ["source_readiness_review_not_ready"],
    },
    managerCandidateReview: {
      scaleUpCandidates: [
        {
          decisionType: "scale_amount",
          entityType: "ad_group",
          entityId: "2001",
          platform: "google",
          accountId: "1234567890",
          productId: "P_SCALE_BLOCKED",
          supplierId: "SUP_STALE",
          status: "blocked_missing_data",
          effectiveStatus: "blocked",
          proposedAction: "update_campaign_budget",
          campaignBudgetId: null,
          currentBudgetVnd: 1000000,
          proposedBudgetVnd: 1200000,
          increaseVnd: 200000,
          conversions: 12,
          conversionValueVnd: 6000000,
          blockers: ["campaignBudgetId_missing_no_fallback"],
          missingFields: ["campaignBudgetId"],
          approval_required: true,
          execution_allowed_now: false,
        },
      ],
      pauseCandidates: [
        {
          decisionType: "campaign_or_ad_group_pause",
          entityType: "campaign",
          entityId: "1001",
          platform: "google",
          accountId: "1234567890",
          productId: "P_LOSS_LIMIT",
          supplierId: null,
          status: "candidate",
          effectiveStatus: "candidate_for_review",
          proposedAction: "pause_campaign",
          campaignBudgetId: null,
          currentBudgetVnd: null,
          proposedBudgetVnd: null,
          increaseVnd: null,
          conversions: 0,
          conversionValueVnd: 0,
          blockers: [],
          missingFields: [],
          approval_required: true,
          execution_allowed_now: false,
        },
      ],
      productKillCandidates: [],
      productAllocationCandidates: [],
      supplierSafetyCandidates: [],
    },
    decisionAnswerReview: {
      may_increase_ads: false,
      max_increase_vnd: 0,
      scale_up_execution_mode: "monitor_only",
      ad_groups_to_increase: [],
      target_ad_groups: [],
      products_can_receive_budget: [],
      blocked_product_budget_candidates: [
        {
          decisionType: "product_budget_allocation",
          entityType: "product",
          entityId: "P_SCALE_BLOCKED",
          platform: "google",
          accountId: "1234567890",
          productId: "P_SCALE_BLOCKED",
          supplierId: "SUP_STALE",
          status: "blocked",
          effectiveStatus: "blocked",
          proposedAction: null,
          campaignBudgetId: null,
          currentBudgetVnd: null,
          proposedBudgetVnd: null,
          increaseVnd: null,
          blockers: ["inventory_profit_not_ready_for_ads_automation_decision"],
          missingFields: ["inventory_profit"],
          approval_required: true,
          execution_allowed_now: false,
        },
      ],
      supplier_choice_safe: false,
      safe_supplier_choices: [],
      blocked_supplier_choices: [
        {
          decisionType: "supplier_gate",
          entityType: "supplier",
          entityId: "SUP_STALE",
          platform: "google",
          accountId: "1234567890",
          productId: "P_SCALE_BLOCKED",
          supplierId: "SUP_STALE",
          status: "blocked",
          effectiveStatus: "blocked",
          proposedAction: null,
          campaignBudgetId: null,
          currentBudgetVnd: null,
          proposedBudgetVnd: null,
          increaseVnd: null,
          blockers: ["supplier_safety_not_ready_for_ads_automation_decision"],
          missingFields: ["supplier_safety"],
          approval_required: true,
          execution_allowed_now: false,
        },
      ],
      product_kill_or_stop_review_needed: false,
      product_kill_or_stop_review: [],
      campaign_or_ad_group_pause_recommended: true,
      campaign_or_ad_group_pause: [
        {
          decisionType: "campaign_or_ad_group_pause",
          entityType: "campaign",
          entityId: "1001",
          platform: "google",
          accountId: "1234567890",
          productId: "P_LOSS_LIMIT",
          supplierId: null,
          status: "needs_review",
          effectiveStatus: "candidate_for_review",
          proposedAction: "pause_campaign",
          campaignBudgetId: null,
          currentBudgetVnd: null,
          proposedBudgetVnd: null,
          increaseVnd: null,
          blockers: [],
          missingFields: [],
          approval_required: true,
          execution_allowed_now: false,
        },
      ],
      blocking_reasons: [
        "source_readiness_review_not_ready",
        "campaignBudgetId_missing_no_fallback",
        "cashflow_first_scale_mode_monitor_only",
      ],
      execution_allowed_now: false,
    },
  } as any,
  validateOnlyLane: {
    schemaVersion: "ads_automation_provider_validate_only_lane.v1",
    generatedAt: "2026-07-04T07:35:00.000Z",
    sourceNormalizationSchemaVersion:
      "ads_automation_pending_erp_action_normalization.v1",
    sourceNormalizationGeneratedAt: "2026-07-04T07:30:00.000Z",
    safety: {
      read_only: true,
      dry_run: true,
      in_memory_only: true,
      persistence_used: false,
      durable_storage_used: false,
      erp_local_persistence_used: false,
      provider_persistence_used: false,
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      erp_mutation_used: false,
      payment_mutation_used: false,
      production_ready: false,
      approval_required_for_all_actions: true,
      approval_can_be_considered_executable_only_after_validateOnly_passed: true,
      execution_allowed_now: false,
      provider_validateOnly_lane_mocked: true,
      no_direct_google_ads_api_call: true,
      campaignBudgetId_no_fallback: true,
    },
    summary: {
      pending_actions_received: 2,
      provider_actions_received: 2,
      non_provider_actions_skipped: 0,
      validate_only_pending: 0,
      validate_only_passed: 1,
      validate_only_failed: 0,
      blocked_before_validate_only: 1,
      approval_can_be_considered_executable: 1,
      executable_now: 0,
    },
    validationPlans: [
      {
        validation_id:
          "ADSPROVIDERVALIDATE-approval-preflight-demo-scale-missing-budget",
        pending_action_id:
          "ADSPENDINGACTION-approval-preflight-demo-scale-missing-budget",
        approval_id: SCALE_APPROVAL_ID,
        source_pending_action_status: "pending_validation",
        action_type: "update_campaign_budget",
        action_family: "provider_google_ads",
        provider: "google",
        resource_type: "campaign_budget",
        entity_type: "ad_group",
        entity_id: "2001",
        customerId: "1234567890",
        campaignId: "1001",
        adGroupId: "2001",
        campaignBudgetId: null,
        campaignBudgetResourceName: null,
        requested_change: scaleApproval.typedPayload,
        status: "blocked_before_validate_only",
        providerValidationStatus: "pending",
        providerRequestId: null,
        providerValidatedAt: null,
        providerValidationErrors: [],
        before_state_snapshot: {
          snapshot_status: "placeholder_pending_erp_synced_read",
          required_before_future_execution: true,
          source: "erp_synced_google_ads_read_model",
          customerId: "1234567890",
          campaignId: "1001",
          adGroupId: "2001",
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
          snapshot: null,
        },
        provider_boundary_evidence: {
          boundary_mode: "erp_local_mock_only",
          status_source: "preflight_blockers",
          mocked_provider_result_used: false,
          provider_api_called: false,
          google_ads_api_called: false,
          validateOnly_called: false,
          direct_google_ads_api_call: false,
          operation_builder_called: false,
          raw_provider_request_included: false,
          evidence: [
            "Blocked before validateOnly because campaignBudgetId and source readiness are unsafe.",
          ],
        },
        mvp_action_contract: {
          supported_mvp_action: true,
          action_scope: "provider_validateOnly_required",
          preflight_treatment: "eligible_for_future_provider_preflight",
          provider_validateOnly_required_before_future_execution: true,
          monitor_only_safety_action: false,
          visible_as_safety_action: false,
          approval_required_before_execution: true,
          future_live_execution_allowed: false,
          executable_now: false,
          execution_allowed_now: false,
          provider_api_called: false,
          google_ads_api_called: false,
          validateOnly_called: false,
          live_ads_execution_used: false,
        },
        blockers: ["campaignBudgetId", "freshness_stale"],
        approval_can_be_considered_executable: false,
        executable_now: false,
        execution_allowed_now: false,
        validate_only_required_before_execution: true,
        next_required_action: "fix_blockers_before_validateOnly",
        source_pending_action: {},
      },
      {
        validation_id:
          "ADSPROVIDERVALIDATE-approval-preflight-demo-pause-campaign",
        pending_action_id:
          "ADSPENDINGACTION-approval-preflight-demo-pause-campaign",
        approval_id: PAUSE_APPROVAL_ID,
        source_pending_action_status: "pending_validation",
        action_type: "pause_campaign",
        action_family: "provider_google_ads",
        provider: "google",
        resource_type: "campaign",
        entity_type: "campaign",
        entity_id: "1001",
        customerId: "1234567890",
        campaignId: "1001",
        adGroupId: null,
        campaignBudgetId: null,
        campaignBudgetResourceName: null,
        requested_change: pauseApproval.typedPayload,
        status: "validate_only_passed",
        providerValidationStatus: "provider_validate_passed",
        providerRequestId: "REQ-VALIDATE-PAUSE-DEMO",
        providerValidatedAt: "2026-07-04T07:40:00.000Z",
        providerValidationErrors: [],
        before_state_snapshot: {
          snapshot_status: "mocked_boundary_snapshot",
          required_before_future_execution: true,
          source: "erp_synced_google_ads_read_model",
          customerId: "1234567890",
          campaignId: "1001",
          adGroupId: null,
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
          snapshot: { status: "ENABLED" },
        },
        provider_boundary_evidence: {
          boundary_mode: "erp_local_mock_only",
          status_source: "mock_provider_result",
          mocked_provider_result_used: true,
          provider_api_called: false,
          google_ads_api_called: false,
          validateOnly_called: false,
          direct_google_ads_api_call: false,
          operation_builder_called: false,
          raw_provider_request_included: false,
          evidence: ["Mock validateOnly passed; no provider API was called."],
        },
        mvp_action_contract: {
          supported_mvp_action: true,
          action_scope: "provider_validateOnly_required",
          preflight_treatment: "eligible_for_future_provider_preflight",
          provider_validateOnly_required_before_future_execution: true,
          monitor_only_safety_action: false,
          visible_as_safety_action: false,
          approval_required_before_execution: true,
          future_live_execution_allowed: false,
          executable_now: false,
          execution_allowed_now: false,
          provider_api_called: false,
          google_ads_api_called: false,
          validateOnly_called: false,
          live_ads_execution_used: false,
        },
        blockers: [],
        approval_can_be_considered_executable: true,
        executable_now: false,
        execution_allowed_now: false,
        validate_only_required_before_execution: true,
        next_required_action: "continue_human_approval_flow",
        source_pending_action: {},
      },
    ],
  } as any,
  pendingApprovals: [scaleApproval, pauseApproval],
  approvalDecisionAuditRecords: [
    {
      schemaVersion:
        "ads_automation_decision_draft_approval_decision_audit_record.v1",
      audit_id: "ADSAUDIT-approval-preflight-demo-pause-campaign-approve",
      idempotency_key:
        "ads-decision-audit:pause-campaign:approve:REQ-PAUSE-DEMO",
      approval_id: PAUSE_APPROVAL_ID,
      source_draft_id: pauseApproval.source_draft_id,
      source_decision_id: pauseApproval.source_decision_id,
      action_type: "pause_campaign",
      action_family: "provider_google_ads",
      provider: "google",
      resource_type: "campaign",
      entity_type: "campaign",
      entity_id: "1001",
      accountId: "1234567890",
      productId: "P_LOSS_LIMIT",
      supplierId: null,
      platform: "google",
      previous_status: "pending_approval",
      proposed_status: "approved",
      decision: "approve",
      reviewerUserId: "director-1",
      reviewerRole: "director",
      reason: "Approve pause safety action after ERP loss review.",
      requestId: "REQ-PAUSE-DEMO",
      validation_status: "eligible_for_human_decision",
      prerequisites_valid: 12,
      prerequisites_blocked: 0,
      blockers: [],
      prerequisites: [],
      pending_approval_snapshot: pauseApproval,
      audit_record_persisted: true,
      status_change_performed: true,
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      erp_mutation_used: false,
      payment_mutation_used: false,
      execution_allowed_now: false,
      persistence_used: true,
      durable_storage_used: true,
      erp_local_persistence_used: true,
      provider_persistence_used: false,
      storage: "erp_local_mongo",
      source_preview_createdAt: pauseApproval.createdAt,
      createdAt: "2026-07-04T07:45:00.000Z",
      persistedAt: "2026-07-04T07:45:00.000Z",
    },
  ],
  executionPreflightDryRun: {
    schemaVersion: "ads_automation_execution_preflight_dry_run.v1",
    generatedAt: "2026-07-04T07:50:00.000Z",
    safety: {
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      execution_allowed_now: false,
      production_ready: false,
    },
    summary: {
      approvals_requested: 2,
      approvals_loaded: 2,
      records_created: 2,
      supported_action_records: 2,
      unsupported_action_records: 0,
      future_live_gates_passed_local_only: 0,
      blocked_before_future_live_execution: 2,
      dry_run_records_created: 2,
      dry_run_records_persisted: 2,
      idempotent_records_reused: 0,
      idempotent_duplicate_records_blocked: 0,
      approval_decision_audit_records_received: 1,
      source_readiness_blocked_records: 1,
      kill_switch_blocked_records: 1,
      executable_now: 0,
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
    },
    executionReadinessContract: {
      schemaVersion: "ads_automation_execution_preflight_readiness_contract.v1",
      supported_mvp_actions: [
        "update_campaign_budget",
        "pause_campaign",
        "pause_ad_group",
        "monitor_only",
      ],
      required_gate_families: EXECUTION_READINESS_GATE_FAMILIES,
      must_have_before_future_live_execution:
        EXECUTION_READINESS_MUST_HAVE_BEFORE_FUTURE_LIVE,
      action_type_coverage: [
        {
          action_type: "update_campaign_budget",
          records_checked: 1,
          records_blocked: 1,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 1,
          validateOnly_missing_or_blocked_records: 1,
          validateOnly_passed_records: 0,
          approval_missing_or_blocked_records: 1,
          approval_audit_missing_or_blocked_records: 1,
          source_readiness_blocked_records: 1,
          finance_policy_blocked_records: 1,
          kill_switch_blocked_records: 1,
          idempotency_blocked_records: 1,
          campaignBudgetId_blocked_records: 1,
          production_flag_blocked_records: 1,
          live_path_blocked_records: 1,
          scale_candidate: true,
          safety_action: false,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
        {
          action_type: "pause_campaign",
          records_checked: 1,
          records_blocked: 1,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 1,
          validateOnly_missing_or_blocked_records: 0,
          validateOnly_passed_records: 1,
          approval_missing_or_blocked_records: 0,
          approval_audit_missing_or_blocked_records: 0,
          source_readiness_blocked_records: 0,
          finance_policy_blocked_records: 0,
          kill_switch_blocked_records: 0,
          idempotency_blocked_records: 0,
          campaignBudgetId_blocked_records: 0,
          production_flag_blocked_records: 1,
          live_path_blocked_records: 1,
          scale_candidate: false,
          safety_action: true,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
        {
          action_type: "pause_ad_group",
          records_checked: 0,
          records_blocked: 0,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 0,
          validateOnly_missing_or_blocked_records: 0,
          validateOnly_passed_records: 0,
          approval_missing_or_blocked_records: 0,
          approval_audit_missing_or_blocked_records: 0,
          source_readiness_blocked_records: 0,
          finance_policy_blocked_records: 0,
          kill_switch_blocked_records: 0,
          idempotency_blocked_records: 0,
          campaignBudgetId_blocked_records: 0,
          production_flag_blocked_records: 0,
          live_path_blocked_records: 0,
          scale_candidate: false,
          safety_action: true,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
        {
          action_type: "monitor_only",
          records_checked: 0,
          records_blocked: 0,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 0,
          validateOnly_missing_or_blocked_records: 0,
          validateOnly_passed_records: 0,
          approval_missing_or_blocked_records: 0,
          approval_audit_missing_or_blocked_records: 0,
          source_readiness_blocked_records: 0,
          finance_policy_blocked_records: 0,
          kill_switch_blocked_records: 0,
          idempotency_blocked_records: 0,
          campaignBudgetId_blocked_records: 0,
          production_flag_blocked_records: 0,
          live_path_blocked_records: 0,
          scale_candidate: false,
          safety_action: true,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
      ],
      gate_coverage: {
        records_checked: 2,
        blocked_gate_families: EXECUTION_READINESS_GATE_FAMILIES,
        scale_candidate_blocker_families: EXECUTION_READINESS_GATE_FAMILIES,
        scale_candidate_blocked_by_all_gate_families: true,
        required_pre_live_gates_passed_records: 0,
        required_pre_live_gates_blocked_records: 2,
        validateOnly_missing_or_blocked_records: 1,
        validateOnly_passed_records: 1,
        approval_missing_or_blocked_records: 1,
        approval_audit_missing_or_blocked_records: 1,
        source_readiness_blocked_records: 1,
        finance_policy_blocked_records: 1,
        kill_switch_blocked_records: 1,
        idempotency_blocked_records: 1,
        campaignBudgetId_blocked_records: 1,
        production_flag_blocked_records: 2,
        live_path_blocked_records: 2,
      },
      safety_action_visibility: {
        pause_safety_records_visible: 1,
        monitor_only_safety_records_visible: 1,
        safety_action_records_visible: 2,
      },
      non_execution_guarantee: {
        executable_now_actions: 0,
        provider_api_called: false,
        provider_api_used: false,
        google_ads_api_called: false,
        google_ads_api_used: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        execution_allowed_now: false,
        production_ready: false,
      },
    },
    executionRecords: [
      {
        execution_record_id:
          "ADSEXEC-DRYRUN-approval-preflight-demo-scale-missing-budget",
        idempotency_key: "ads execution unsafe whitespace",
        approval_id: SCALE_APPROVAL_ID,
        source_draft_id: scaleApproval.source_draft_id,
        source_decision_id: scaleApproval.source_decision_id,
        action_type: "update_campaign_budget",
        action_family: "provider_google_ads",
        provider: "google",
        resource_type: "campaign_budget",
        entity_type: "ad_group",
        entity_id: "2001",
        accountId: "1234567890",
        platform: "google",
        approval_status: "pending_approval",
        approval_decision_audit_id: null,
        approval_decision_audit_persisted: false,
        source_readiness_safe: false,
        kill_switch_active: true,
        kill_switch_reason: "director_emergency_stop_active",
        validateOnly_validation_id:
          "ADSPROVIDERVALIDATE-approval-preflight-demo-scale-missing-budget",
        validateOnly_evidence_persisted: true,
        validateOnly_status: "blocked_before_validate_only",
        policy_decision_id: null,
        policy_decision_evidence_persisted: false,
        policy_allowed: false,
        google_ads_production_enabled: false,
        preflight_status: "blocked_before_future_live_execution",
        future_live_execution_allowed: false,
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        live_path_implemented: false,
        campaignBudgetId_fallback_used: false,
        requested_change: scaleApproval.typedPayload,
        identifiers: {
          customerId: "1234567890",
          campaignId: "1001",
          adGroupId: "2001",
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
        },
        blockers: [
          "source_readiness_safe",
          "source_readiness.source_sync_gate_blocked_action_draft",
          "source_readiness.freshness_stale",
          "campaignBudgetId",
          "validateOnly_plan_found",
          "validateOnly_passed",
          "approved_action",
          "approval_decision_audit_found",
          "approval_decision_audit_missing",
          "policy_allowed",
          "policy_decision_missing",
          "kill_switch_off",
          "kill_switch_active",
          "kill_switch.director_emergency_stop_active",
          "idempotency_key_safe",
          "GOOGLE_ADS_PRODUCTION_ENABLED",
        ],
        gates: [],
        next_required_action: "fix_preflight_blockers_before_future_execution",
        source_pending_approval: scaleApproval,
        source_validateOnly_plan: null,
        policy_decision: null,
      },
      {
        execution_record_id:
          "ADSEXEC-DRYRUN-approval-preflight-demo-pause-campaign",
        idempotency_key:
          "ads-execution-preflight:pause-campaign:REQ-PAUSE-DEMO",
        approval_id: PAUSE_APPROVAL_ID,
        source_draft_id: pauseApproval.source_draft_id,
        source_decision_id: pauseApproval.source_decision_id,
        action_type: "pause_campaign",
        action_family: "provider_google_ads",
        provider: "google",
        resource_type: "campaign",
        entity_type: "campaign",
        entity_id: "1001",
        accountId: "1234567890",
        platform: "google",
        approval_status: "approved",
        approval_decision_audit_id:
          "ADSAUDIT-approval-preflight-demo-pause-campaign-approve",
        approval_decision_audit_persisted: true,
        source_readiness_safe: true,
        kill_switch_active: false,
        kill_switch_reason: null,
        validateOnly_validation_id:
          "ADSPROVIDERVALIDATE-approval-preflight-demo-pause-campaign",
        validateOnly_evidence_persisted: true,
        validateOnly_status: "validate_only_passed",
        policy_decision_id: "ADSPOLICY-approval-preflight-demo-pause-campaign",
        policy_decision_evidence_persisted: true,
        policy_allowed: true,
        google_ads_production_enabled: false,
        preflight_status: "blocked_before_future_live_execution",
        future_live_execution_allowed: false,
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        live_path_implemented: false,
        campaignBudgetId_fallback_used: false,
        requested_change: pauseApproval.typedPayload,
        identifiers: {
          customerId: "1234567890",
          campaignId: "1001",
          adGroupId: null,
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
        },
        blockers: ["GOOGLE_ADS_PRODUCTION_ENABLED"],
        gates: [],
        next_required_action: "fix_preflight_blockers_before_future_execution",
        source_pending_approval: pauseApproval,
        source_validateOnly_plan: null,
        policy_decision: null,
      },
    ],
  } as any,
  monitorOnlyActions: [
    {
      action_id:
        "ADSMONITOR-approval-preflight-demo-cashflow-first-monitor-only",
      action_type: "monitor_only",
      action_family: "monitoring",
      source_decision_id: "DEC-monitor-only-cashflow-first",
      entity_id: "P_SCALE_BLOCKED",
      accountId: "1234567890",
      productId: "P_SCALE_BLOCKED",
      supplierId: "SUP_STALE",
      rationale:
        "Cashflow-first policy preserves capital while source and finance evidence is incomplete.",
      blockers: ["scale_downgraded_to_monitor_only"],
      rollback_plan:
        "No provider rollback needed because monitor_only performs no provider mutation.",
      idempotency_key: "ads-monitor-only:2026-07-04:cashflow-first",
    },
  ],
} as AdsAutomationApprovalPreflightReviewExportInput;
