import type {
  AdsAutomationProviderAccountReadinessInput,
} from './contracts/ads-automation-provider-account-readiness.contract';

export const ADS_AUTOMATION_PROVIDER_ACCOUNT_READINESS_FIXTURE:
  AdsAutomationProviderAccountReadinessInput = {
    reportDate: '2026-07-04',
    now: '2026-07-04T05:00:00.000Z',
    fixtureMode: 'htx_ads_provider_account_readiness_demo',
    accounts: [
      {
        platform: 'google_ads',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        loginCustomerId: '5555555555',
        managerCustomerId: '5555555555',
        erpAccountMappingId: 'ERP-GADS-MAP-PRIMARY',
        accountName: 'HTX Bach Gia - Primary',
        adapterRegistered: true,
        adapterMode: 'contract_only',
        isActive: true,
        approvedForProviderActions: true,
        approvedForReadOnlyImport: true,
        googleAdsProductionEnabled: false,
        credentialMetadata: {
          credentialReferenceId: 'credref-google-ads-primary',
          redactedCredentialReference: 'google_ads_oauth_ref:***primary',
          oauthConnectionStatus: 'ready',
          grantedScopes: [
            'ads.readonly',
            'ads.validate_only',
            'ads.manage_budgets',
            'ads.pause',
          ],
          plaintextCredentialFieldNames: [],
        },
      },
    ],
    requestedActions: [
      {
        actionId: 'PROVIDER-ACTION-BUDGET-2001',
        sourcePendingActionId: 'ADSPENDINGACTION-ads-draft_2026-07-04_update_campaign_budget_2001',
        approvalId: 'ADSAPPROVAL-ads-draft_2026-07-04_update_campaign_budget_2001',
        platform: 'google_ads',
        channel: 'search',
        actionType: 'update_campaign_budget',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1001',
        adGroupId: '2001',
        campaignBudgetId: '3001',
        campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
        currentDailyBudgetVnd: 1000000,
        requestedDailyBudgetVnd: 1200000,
      },
      {
        actionId: 'PROVIDER-ACTION-PAUSE-CAMPAIGN-1001',
        sourcePendingActionId: 'ADSPENDINGACTION-ads-draft_2026-07-04_pause_campaign_1001',
        approvalId: 'ADSAPPROVAL-ads-draft_2026-07-04_pause_campaign_1001',
        platform: 'google_ads',
        channel: 'search',
        actionType: 'pause_campaign',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1001',
        targetStatus: 'PAUSED',
      },
      {
        actionId: 'PROVIDER-ACTION-PAUSE-ADGROUP-2001',
        sourcePendingActionId: 'ADSPENDINGACTION-ads-draft_2026-07-04_pause_ad_group_2001',
        approvalId: 'ADSAPPROVAL-ads-draft_2026-07-04_pause_ad_group_2001',
        platform: 'google_ads',
        channel: 'search',
        actionType: 'pause_ad_group',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1001',
        adGroupId: '2001',
        targetStatus: 'PAUSED',
      },
      {
        actionId: 'PROVIDER-ACTION-MONITOR-ONLY-2001',
        platform: 'google_ads',
        channel: 'search',
        actionType: 'monitor_only',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1001',
        adGroupId: '2001',
      },
    ],
  };
