import { ADS_AUTOMATION_PRODUCTION_READINESS_BRIDGE_FIXTURE } from "./ads-automation-production-readiness-bridge.fixture";
import type {
  AdsAutomationExecutionPreflightDryRunResponse,
  AdsAutomationExecutionPreflightGateFamilyKey,
} from "./contracts/ads-automation-execution-preflight-dry-run.contract";
import type { AdsAutomationFinalGateReviewExportInput } from "./contracts/ads-automation-final-gate-review-export.contract";

export const ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES: AdsAutomationExecutionPreflightGateFamilyKey[] =
  [
    "future_execution_action_scope",
    "approval_status",
    "approval_decision_audit",
    "source_readiness",
    "validateOnly",
    "finance_policy",
    "kill_switch",
    "idempotency",
    "production_flag",
    "provider_identifiers",
    "live_path",
  ];

const BLOCKERS_BY_GATE_FAMILY: Record<
  AdsAutomationExecutionPreflightGateFamilyKey,
  string[]
> = {
  future_execution_action_scope: ["provider_google_ads_action"],
  approval_status: ["approved_action_missing_or_not_executable"],
  approval_decision_audit: ["approval_decision_audit_missing"],
  source_readiness: ["source_readiness.freshness_stale"],
  validateOnly: ["validateOnly_missing"],
  finance_policy: ["policy_decision_missing"],
  kill_switch: ["kill_switch_active"],
  idempotency: ["idempotency_duplicate_record"],
  production_flag: ["GOOGLE_ADS_PRODUCTION_ENABLED"],
  provider_identifiers: ["campaignBudgetId"],
  live_path: ["live_path_not_implemented"],
};

const SCALE_APPROVAL_ID = "ADSAPPROVAL-final-review-scale-blocked";
const PAUSE_APPROVAL_ID = "ADSAPPROVAL-final-review-pause-safety";
const MONITOR_APPROVAL_ID = "ADSAPPROVAL-final-review-monitor-only";
const MUST_HAVE_BEFORE_FUTURE_LIVE_EXECUTION = [
  "approved_action_present",
  "approval_decision_audit_persisted",
  "source_readiness_safe",
  "validateOnly_status_passed",
  "finance_policy_allowed",
  "kill_switch_off",
  "safe_idempotency_key",
  "campaignBudgetId_present_for_update_campaign_budget",
  "preflight_dry_run_record_persisted",
  "GOOGLE_ADS_PRODUCTION_ENABLED_true",
  "live_executor_path_implemented_later",
];

export const ADS_AUTOMATION_FINAL_GATE_REVIEW_PREFLIGHT_FIXTURE: AdsAutomationExecutionPreflightDryRunResponse =
  {
    schemaVersion: "ads_automation_execution_preflight_dry_run.v1",
    generatedAt: "2026-07-06T07:15:00.000Z",
    safety: {
      read_only: false,
      dry_run: true,
      in_memory_only: false,
      persistence_used: true,
      durable_storage_used: true,
      erp_local_persistence_used: true,
      provider_persistence_used: false,
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      erp_mutation_used: false,
      payment_mutation_used: false,
      production_ready: false,
      approval_required_for_all_records: true,
      execution_allowed_now: false,
      dry_run_execution_records_created: true,
      dry_run_execution_records_persisted: true,
      idempotency_enforced: true,
      live_path_implemented: false,
      provider_mutation_used: false,
      direct_google_ads_api_call: false,
      future_live_execution_requires_validateOnly_passed: true,
      future_live_execution_requires_approved_action: true,
      future_live_execution_requires_approval_decision_audit: true,
      future_live_execution_requires_source_readiness_safe: true,
      future_live_execution_requires_policy_allowed: true,
      future_live_execution_requires_kill_switch_off: true,
      future_live_execution_requires_safe_idempotency_key: true,
      future_live_execution_requires_GOOGLE_ADS_PRODUCTION_ENABLED_true: true,
      supported_mvp_actions_limited_to_update_budget_pause_campaign_pause_ad_group_monitor_only: true,
      monitor_only_visible_as_non_executable_safety_action: true,
      campaignBudgetId_no_fallback: true,
      validateOnly_id_linkage_supported: true,
      validateOnly_evidence_persistence_used: true,
      policy_decision_id_linkage_supported: true,
      policy_decision_evidence_persistence_used: true,
    },
    summary: {
      approvals_requested: 3,
      approvals_loaded: 3,
      records_created: 3,
      supported_action_records: 3,
      unsupported_action_records: 0,
      future_live_gates_passed_local_only: 0,
      blocked_before_future_live_execution: 3,
      dry_run_records_created: 3,
      dry_run_records_persisted: 3,
      idempotent_records_reused: 1,
      idempotent_duplicate_records_blocked: 1,
      approval_decision_audit_records_received: 2,
      source_readiness_blocked_records: 1,
      kill_switch_blocked_records: 1,
      safety_action_records_visible: 2,
      pause_safety_records_visible: 1,
      monitor_only_safety_records_visible: 1,
      gate_families_checked:
        ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES.length,
      gate_families_blocked:
        ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES.length,
      validateOnly_validation_id_references_requested: 1,
      validateOnly_evidence_records_loaded: 1,
      validateOnly_evidence_records_persisted: 1,
      validateOnly_evidence_records_reused: 0,
      policy_decision_id_references_requested: 1,
      policy_decision_records_loaded: 0,
      policy_decision_records_persisted: 1,
      policy_decision_records_reused: 0,
      executable_now: 0,
      provider_api_called: false,
      provider_api_used: false,
      google_ads_api_called: false,
      google_ads_api_used: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      execution_allowed_now: false,
      production_ready: false,
      next_required_action: "fix_preflight_blockers_before_future_execution",
    },
    blockerCoverage: {
      required_gate_families: ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES,
      blocked_gate_families: ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES,
      missing_required_gate_family_evidence: [],
      scale_candidate_blocker_families:
        ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES,
      scale_candidate_blocked_by_all_gate_families: true,
      validateOnly_missing_or_blocked_records: 1,
      validateOnly_passed_records: 1,
      approval_missing_or_blocked_records: 1,
      approval_audit_missing_or_blocked_records: 1,
      source_readiness_blocked_records: 1,
      finance_policy_blocked_records: 1,
      kill_switch_blocked_records: 1,
      idempotency_blocked_records: 1,
      campaignBudgetId_blocked_records: 1,
      production_flag_blocked_records: 3,
      live_path_blocked_records: 3,
      pause_safety_records_visible: 1,
      monitor_only_safety_records_visible: 1,
      safety_action_records_visible: 2,
      executable_now_actions: 0,
      provider_api_called: false,
      provider_api_used: false,
      google_ads_api_called: false,
      google_ads_api_used: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      execution_allowed_now: false,
      production_ready: false,
    },
    executionReadinessContract: {
      schemaVersion: "ads_automation_execution_preflight_readiness_contract.v1",
      supported_mvp_actions: [
        "update_campaign_budget",
        "pause_campaign",
        "pause_ad_group",
        "monitor_only",
      ],
      required_gate_families: ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES,
      must_have_before_future_live_execution:
        MUST_HAVE_BEFORE_FUTURE_LIVE_EXECUTION,
      action_type_coverage: [
        {
          action_type: "update_campaign_budget",
          records_checked: 1,
          records_blocked: 1,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 1,
          validateOnly_missing_or_blocked_records: 1,
          validateOnly_passed_records: 0,
          approval_missing_or_blocked_records: 1,
          approval_audit_missing_or_blocked_records: 1,
          source_readiness_blocked_records: 1,
          finance_policy_blocked_records: 1,
          kill_switch_blocked_records: 1,
          idempotency_blocked_records: 1,
          campaignBudgetId_blocked_records: 1,
          production_flag_blocked_records: 1,
          live_path_blocked_records: 1,
          scale_candidate: true,
          safety_action: false,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
        {
          action_type: "pause_campaign",
          records_checked: 0,
          records_blocked: 0,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 0,
          validateOnly_missing_or_blocked_records: 0,
          validateOnly_passed_records: 0,
          approval_missing_or_blocked_records: 0,
          approval_audit_missing_or_blocked_records: 0,
          source_readiness_blocked_records: 0,
          finance_policy_blocked_records: 0,
          kill_switch_blocked_records: 0,
          idempotency_blocked_records: 0,
          campaignBudgetId_blocked_records: 0,
          production_flag_blocked_records: 0,
          live_path_blocked_records: 0,
          scale_candidate: false,
          safety_action: true,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
        {
          action_type: "pause_ad_group",
          records_checked: 1,
          records_blocked: 1,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 1,
          validateOnly_missing_or_blocked_records: 0,
          validateOnly_passed_records: 1,
          approval_missing_or_blocked_records: 0,
          approval_audit_missing_or_blocked_records: 0,
          source_readiness_blocked_records: 0,
          finance_policy_blocked_records: 0,
          kill_switch_blocked_records: 0,
          idempotency_blocked_records: 0,
          campaignBudgetId_blocked_records: 0,
          production_flag_blocked_records: 1,
          live_path_blocked_records: 1,
          scale_candidate: false,
          safety_action: true,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
        {
          action_type: "monitor_only",
          records_checked: 1,
          records_blocked: 1,
          required_pre_live_gates_passed_records: 0,
          required_pre_live_gates_blocked_records: 1,
          validateOnly_missing_or_blocked_records: 1,
          validateOnly_passed_records: 0,
          approval_missing_or_blocked_records: 0,
          approval_audit_missing_or_blocked_records: 0,
          source_readiness_blocked_records: 0,
          finance_policy_blocked_records: 0,
          kill_switch_blocked_records: 0,
          idempotency_blocked_records: 0,
          campaignBudgetId_blocked_records: 0,
          production_flag_blocked_records: 1,
          live_path_blocked_records: 1,
          scale_candidate: false,
          safety_action: true,
          executable_now_actions: 0,
          execution_allowed_now: false,
          production_ready: false,
        },
      ],
      gate_coverage: {
        records_checked: 3,
        blocked_gate_families: ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES,
        scale_candidate_blocker_families:
          ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES,
        scale_candidate_blocked_by_all_gate_families: true,
        required_pre_live_gates_passed_records: 0,
        required_pre_live_gates_blocked_records: 3,
        validateOnly_missing_or_blocked_records: 1,
        validateOnly_passed_records: 1,
        approval_missing_or_blocked_records: 1,
        approval_audit_missing_or_blocked_records: 1,
        source_readiness_blocked_records: 1,
        finance_policy_blocked_records: 1,
        kill_switch_blocked_records: 1,
        idempotency_blocked_records: 1,
        campaignBudgetId_blocked_records: 1,
        production_flag_blocked_records: 3,
        live_path_blocked_records: 3,
      },
      safety_action_visibility: {
        pause_safety_records_visible: 1,
        monitor_only_safety_records_visible: 1,
        safety_action_records_visible: 2,
      },
      non_execution_guarantee: {
        executable_now_actions: 0,
        provider_api_called: false,
        provider_api_used: false,
        google_ads_api_called: false,
        google_ads_api_used: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        execution_allowed_now: false,
        production_ready: false,
      },
    },
    gateFamilyEvidence: ADS_AUTOMATION_FINAL_GATE_REVIEW_GATE_FAMILIES.map(
      (key) => ({
        key,
        status: "blocked",
        records_checked: 3,
        records_blocked:
          key === "production_flag" || key === "live_path" ? 3 : 1,
        blocked_approval_ids:
          key === "production_flag" || key === "live_path"
            ? [MONITOR_APPROVAL_ID, PAUSE_APPROVAL_ID, SCALE_APPROVAL_ID]
            : [SCALE_APPROVAL_ID],
        blocker_keys: BLOCKERS_BY_GATE_FAMILY[key],
      }),
    ),
    executionRecords: [
      {
        approval_id: SCALE_APPROVAL_ID,
        action_type: "update_campaign_budget",
        validateOnly_status: "missing",
        preflight_status: "blocked_before_future_live_execution",
        blockers: Object.values(BLOCKERS_BY_GATE_FAMILY).flat(),
        gates: [
          {
            key: "campaignBudgetId",
            status: "blocked",
            detail:
              "campaignBudgetId missing; no campaignId or adGroupId fallback allowed",
          },
        ],
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        production_ready: false,
        future_live_execution_allowed: false,
        identifiers: {
          customerId: "1112223333",
          campaignId: "demo-campaign-001",
          adGroupId: "demo-ad-group-001",
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
        },
        campaignBudgetId_fallback_used: false,
      },
      {
        approval_id: PAUSE_APPROVAL_ID,
        action_type: "pause_ad_group",
        validateOnly_status: "validate_only_passed",
        preflight_status: "blocked_before_future_live_execution",
        blockers: [
          "GOOGLE_ADS_PRODUCTION_ENABLED",
          "live_path_not_implemented",
        ],
        gates: [],
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        production_ready: false,
        future_live_execution_allowed: false,
        identifiers: {
          customerId: "1112223333",
          campaignId: "demo-campaign-001",
          adGroupId: "demo-ad-group-002",
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
        },
        campaignBudgetId_fallback_used: false,
      },
      {
        approval_id: MONITOR_APPROVAL_ID,
        action_type: "monitor_only",
        validateOnly_status: "missing",
        preflight_status: "blocked_before_future_live_execution",
        blockers: [
          "provider_google_ads_action",
          "GOOGLE_ADS_PRODUCTION_ENABLED",
          "live_path_not_implemented",
        ],
        gates: [],
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        production_ready: false,
        future_live_execution_allowed: false,
        identifiers: {
          customerId: "1112223333",
          campaignId: "demo-campaign-001",
          adGroupId: "demo-ad-group-001",
          campaignBudgetId: null,
          campaignBudgetResourceName: null,
        },
        campaignBudgetId_fallback_used: false,
      },
    ] as any,
  };

export const ADS_AUTOMATION_FINAL_GATE_REVIEW_EXPORT_FIXTURE: AdsAutomationFinalGateReviewExportInput =
  {
    reportDate: "2026-07-06",
    now: "2026-07-06T07:20:00.000Z",
    fixtureMode: "htx_ads_final_gate_review_demo",
    executionPreflightResponse:
      ADS_AUTOMATION_FINAL_GATE_REVIEW_PREFLIGHT_FIXTURE,
    productionReadinessBridgeInput:
      ADS_AUTOMATION_PRODUCTION_READINESS_BRIDGE_FIXTURE,
  };
