import type { AdsAutomationDecisionSnapshotInput } from './contracts/ads-automation-decision.contract';

export const ADS_AUTOMATION_DECISION_FOUNDATION_SNAPSHOT_FIXTURE: AdsAutomationDecisionSnapshotInput = {
  snapshotDate: '2026-07-04',
  evidenceWindow: { from: '2026-06-21', to: '2026-07-04', days: 14 },
  policy: {
    availableAdsCashVnd: 500000,
    cashflowGatePassed: true,
    maxBudgetIncreasePercent: 20,
    mediumConfidenceIncreasePercent: 10,
    minOrdersForScale: 5,
    minDataQualityScore: 0.75,
    minSpendForPauseVnd: 200000,
    maxReturnRatePercent: 25,
    minMarginPercent: 20,
    minStockAvailable: 10,
    minDaysOfCover: 7,
    maxSupplierLeadTimeDays: 10,
    maxSupplierLateDeliveryRatePercent: 15,
    maxSupplierReturnFaultRatePercent: 12,
    maxSupplierPaymentFreshnessDays: 30,
  },
  adGroups: [
    {
      platform: 'google',
      accountId: '1234567890',
      campaignId: 'CAMP_SCALE',
      campaignName: 'Search - Scale',
      adGroupId: 'AG_SCALE',
      adGroupName: 'Profitable rice cooker ad group',
      resourceName: 'customers/1234567890/adGroups/AG_SCALE',
      campaignBudgetId: 'BUDGET_SCALE',
      campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/BUDGET_SCALE',
      currentStatus: 'ENABLED',
      currentBudgetVnd: 1000000,
      spendVnd: 300000,
      clicks: 120,
      impressions: 5000,
      orders: 12,
      revenueVnd: 4000000,
      grossProfitVnd: 1600000,
      netProfitAfterAdsVnd: 700000,
      returnRatePercent: 8,
      dataQualityScore: 0.92,
      labels: [],
      productIds: ['P_SCALE'],
      bottlenecksChecked: true,
    },
    {
      platform: 'google',
      accountId: '1234567890',
      campaignId: 'CAMP_PAUSE',
      campaignName: 'Search - Pause Review',
      adGroupId: 'AG_PAUSE',
      adGroupName: 'Refund-heavy pan set ad group',
      resourceName: 'customers/1234567890/adGroups/AG_PAUSE',
      campaignBudgetId: 'BUDGET_PAUSE',
      campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/BUDGET_PAUSE',
      currentStatus: 'ENABLED',
      currentBudgetVnd: 500000,
      spendVnd: 350000,
      clicks: 88,
      impressions: 4100,
      orders: 0,
      revenueVnd: 0,
      grossProfitVnd: 0,
      netProfitAfterAdsVnd: -350000,
      returnRatePercent: 40,
      dataQualityScore: 0.88,
      labels: [],
      productIds: ['P_BAD'],
      bottlenecksChecked: true,
    },
  ],
  products: [
    {
      productId: 'P_SCALE',
      sku: 'SKU-SCALE',
      name: 'Profitable rice cooker',
      netProfitVnd: 1250000,
      adAttributedNetProfitAfterAdsVnd: 700000,
      marginPercent: 45,
      returnCancelRefundRatePercent: 8,
      stockAvailable: 120,
      reservedQuantity: 12,
      incomingQuantity: 80,
      daysOfCover: 20,
      mediaReady: true,
      landingReady: true,
      offerReady: true,
      mappedAdGroupIds: ['AG_SCALE'],
      supplierIds: ['SUP_SAFE'],
    },
    {
      productId: 'P_BAD',
      sku: 'SKU-BAD',
      name: 'Refund-heavy pan set',
      netProfitVnd: -450000,
      adAttributedNetProfitAfterAdsVnd: -350000,
      marginPercent: -5,
      returnCancelRefundRatePercent: 40,
      stockAvailable: 50,
      reservedQuantity: 5,
      incomingQuantity: 0,
      daysOfCover: 12,
      mediaReady: true,
      landingReady: true,
      offerReady: true,
      mappedAdGroupIds: ['AG_PAUSE'],
      supplierIds: ['SUP_WEAK_1', 'SUP_WEAK_2'],
    },
  ],
  suppliers: [
    {
      productId: 'P_SCALE',
      supplierId: 'SUP_SAFE',
      supplierName: 'Safe Supplier',
      quoteApproved: true,
      currentQuoteVnd: 180000,
      priorQuoteVnd: 185000,
      marginAfterCostPercent: 42,
      leadTimeDays: 4,
      lateDeliveryRatePercent: 3,
      paymentFreshnessDays: 5,
      capacityStatus: 'available',
      returnFaultRatePercent: 2,
    },
    {
      productId: 'P_BAD',
      supplierId: 'SUP_WEAK_1',
      supplierName: 'Weak Supplier One',
      quoteApproved: true,
      currentQuoteVnd: 260000,
      priorQuoteVnd: 230000,
      marginAfterCostPercent: 8,
      leadTimeDays: 14,
      lateDeliveryRatePercent: 20,
      paymentFreshnessDays: 45,
      capacityStatus: 'constrained',
      returnFaultRatePercent: 14,
    },
    {
      productId: 'P_BAD',
      supplierId: 'SUP_WEAK_2',
      supplierName: 'Weak Supplier Two',
      quoteApproved: false,
      currentQuoteVnd: 280000,
      priorQuoteVnd: 250000,
      marginAfterCostPercent: -2,
      leadTimeDays: 16,
      lateDeliveryRatePercent: 22,
      paymentFreshnessDays: 60,
      capacityStatus: 'blocked',
      returnFaultRatePercent: 18,
    },
  ],
};
