import type {
  AdsAutomationLossLimitPolicyInput,
} from './contracts/ads-automation-loss-limit-policy.contract';

export const ADS_AUTOMATION_LOSS_LIMIT_POLICY_FIXTURE:
  AdsAutomationLossLimitPolicyInput = {
    reportDate: '2026-07-04',
    now: '2026-07-04T05:00:00.000Z',
    fixtureMode: 'htx_ads_loss_policy_demo',
    action: {
      actionType: 'update_campaign_budget',
      customerId: '1234567890',
      campaignId: '1001',
      adGroupId: '2001',
      campaignBudgetId: '3001',
      campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
      productId: 'P_SCALE',
      currentDailyBudgetVnd: 1000000,
      requestedDailyBudgetVnd: 1300000,
    },
    approval: {
      approvalRequired: true,
      approvalId: 'ADSAPPROVAL-loss-policy-demo-update-budget-2001',
      approvedByUserId: null,
      approvedAt: null,
      status: 'pending',
    },
    globalLimits: {
      dailyLossLimitVnd: 700000,
      currentDailyLossVnd: 760000,
      projectedDailyLossAfterActionVnd: 900000,
      monthToDateLossLimitVnd: 6200000,
      currentMonthToDateLossVnd: 5900000,
      projectedMonthToDateLossAfterActionVnd: 6600000,
      emergencyStopEnabled: false,
      killSwitchEnabled: false,
      killSwitchReason: null,
    },
    spendCaps: [
      {
        scopeType: 'campaign',
        scopeId: '1001',
        campaignBudgetId: '3001',
        currentDailyBudgetVnd: 1000000,
        requestedDailyBudgetVnd: 1300000,
        maxDailyBudgetVnd: 1200000,
        maxIncreasePercent: 20,
        currentMonthSpendVnd: 5300000,
        monthlySpendCapVnd: 6200000,
      },
      {
        scopeType: 'ad_group',
        scopeId: '2001',
        campaignBudgetId: '3001',
        currentDailyBudgetVnd: 1000000,
        requestedDailyBudgetVnd: 1300000,
        maxDailyBudgetVnd: 1200000,
        maxIncreasePercent: 20,
        currentMonthSpendVnd: 3100000,
        monthlySpendCapVnd: 3800000,
      },
      {
        scopeType: 'product',
        scopeId: 'P_SCALE',
        currentDailyBudgetVnd: 1000000,
        requestedDailyBudgetVnd: 1300000,
        maxDailyBudgetVnd: 1250000,
        maxIncreasePercent: 20,
        currentMonthSpendVnd: 4700000,
        monthlySpendCapVnd: 4900000,
      },
    ],
    economics: [
      {
        productId: 'P_SCALE',
        adGroupId: '2001',
        grossMarginPercent: 34,
        minGrossMarginPercent: 30,
        contributionProfitVnd: 420000,
        minContributionProfitVnd: 500000,
        cashConversionDays: 39,
        maxCashConversionDays: 21,
        workingCapitalAvailableVnd: 1800000,
        minWorkingCapitalRequiredVnd: 2500000,
        stockCoverageSafe: true,
        supplierReliabilitySafe: true,
        fulfillmentCapacitySafe: false,
        returnRefundRiskSafe: true,
        dataFreshnessSafe: true,
      },
    ],
  };
