import type {
  AdsAutomationManagerAccountControlPlaneInput,
} from './contracts/ads-automation-manager-account-control-plane.contract';

export const ADS_AUTOMATION_MANAGER_ACCOUNT_CONTROL_PLANE_FIXTURE:
  AdsAutomationManagerAccountControlPlaneInput = {
    reportDate: '2026-07-06',
    now: '2026-07-06T06:00:00.000Z',
    fixtureMode: 'htx_ads_manager_account_control_plane_demo',
    managerAccounts: [
      {
        provider: 'google_ads',
        managerAccountType: 'google_ads_mcc',
        managerAccountId: 'demo-gads-mcc-htx-001',
        managerAccountName: 'HTX Bach Gia Google Ads MCC Demo',
        credentialMetadata: {
          credentialReferenceId: 'credref-demo-gads-mcc-001',
          secret_reference_handle: 'erp-vault://ads/google_ads_mcc/demo-***-metadata',
          credentialStatus: 'ready',
          grantedScopes: [
            'ads.readonly',
            'ads.validate_only',
            'ads.manage_budgets',
            'ads.pause',
          ],
          plaintextCredentialFieldNames: [],
          lastCheckedAt: '2026-07-06T05:40:00.000Z',
        },
        childAccounts: [
          {
            childAccountId: 'demo-gads-child-search-001',
            childAccountName: 'HTX Search Child Account Demo',
            erpAccountMappingId: 'ERP-ADS-MAP-GADS-001',
            authorizedUnderManager: true,
            approvedForReadOnlyImport: true,
            approvedForFutureProviderActions: true,
            active: true,
            syncStatus: 'fresh',
            lastSyncAt: '2026-07-06T05:30:00.000Z',
            campaigns: [
              {
                campaignId: 'demo-gads-campaign-scale-001',
                campaignName: 'Local Search Scale Demo',
                channel: 'search',
                status: 'ENABLED',
                campaignBudgetEvidence: {
                  campaignBudgetId: 'demo-gads-budget-001',
                  campaignBudgetResourceName:
                    'customers/demo-gads-child-search-001/campaignBudgets/demo-gads-budget-001',
                  evidenceSource: 'mock_fixture',
                  lastVerifiedAt: '2026-07-06T05:30:00.000Z',
                },
                erpProductMappingStatus: 'mapped',
                supplierMappingStatus: 'mapped',
                orderProfitMappingStatus: 'mapped',
                cashflowMappingStatus: 'mapped',
                adGroups: [
                  {
                    adGroupId: 'demo-gads-adgroup-cooker-001',
                    adGroupName: 'Rice Cooker Exact Demo',
                    erpProductId: 'ERP-PRODUCT-RICE-COOKER-DEMO',
                    erpProductName: 'Rice cooker demo product',
                    supplierId: 'ERP-SUPPLIER-SAFE-DEMO',
                    supplierName: 'Safe supplier demo',
                    erpProductMappingStatus: 'mapped',
                    supplierMappingStatus: 'mapped',
                    profitMappingStatus: 'mapped',
                    stockMappingStatus: 'mapped',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        provider: 'meta_ads',
        managerAccountType: 'meta_business_manager',
        managerAccountId: 'demo-meta-bm-htx-001',
        managerAccountName: 'HTX Bach Gia Meta Business Manager Demo',
        credentialMetadata: {
          credentialReferenceId: 'credref-demo-meta-bm-001',
          secret_reference_handle: 'erp-vault://ads/meta_business_manager/demo-***-metadata',
          credentialStatus: 'ready',
          grantedScopes: [
            'business_management',
            'ads_management',
            'ads.readonly',
            'ads.pause',
            'ads.validate_only',
          ],
          plaintextCredentialFieldNames: [],
          lastCheckedAt: '2026-07-06T05:42:00.000Z',
        },
        childAccounts: [
          {
            childAccountId: 'demo-meta-child-social-001',
            childAccountName: 'HTX Meta Child Ad Account Demo',
            erpAccountMappingId: 'ERP-ADS-MAP-META-001',
            authorizedUnderManager: true,
            approvedForReadOnlyImport: true,
            approvedForFutureProviderActions: true,
            active: true,
            syncStatus: 'fresh',
            lastSyncAt: '2026-07-06T05:31:00.000Z',
            campaigns: [
              {
                campaignId: 'demo-meta-campaign-retarget-001',
                campaignName: 'Local Social Retarget Demo',
                channel: 'social_feed',
                status: 'ACTIVE',
                campaignBudgetEvidence: {
                  campaignBudgetId: 'demo-meta-budget-001',
                  campaignBudgetResourceName:
                    'meta/demo-meta-child-social-001/campaign-budgets/demo-meta-budget-001',
                  evidenceSource: 'mock_fixture',
                  lastVerifiedAt: '2026-07-06T05:31:00.000Z',
                },
                erpProductMappingStatus: 'mapped',
                supplierMappingStatus: 'mapped',
                orderProfitMappingStatus: 'mapped',
                cashflowMappingStatus: 'mapped',
                adGroups: [
                  {
                    adGroupId: 'demo-meta-adset-fan-001',
                    adGroupName: 'Fan Remarketing Demo',
                    erpProductId: 'ERP-PRODUCT-FAN-DEMO',
                    erpProductName: 'Electric fan demo product',
                    supplierId: 'ERP-SUPPLIER-SAFE-DEMO',
                    supplierName: 'Safe supplier demo',
                    erpProductMappingStatus: 'mapped',
                    supplierMappingStatus: 'mapped',
                    profitMappingStatus: 'mapped',
                    stockMappingStatus: 'mapped',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        provider: 'tiktok_ads',
        managerAccountType: 'tiktok_business_center',
        managerAccountId: 'demo-tiktok-bc-htx-001',
        managerAccountName: 'HTX Bach Gia TikTok Business Center Demo',
        credentialMetadata: {
          credentialReferenceId: 'credref-demo-tiktok-bc-001',
          secret_reference_handle: 'erp-vault://ads/tiktok_business_center/demo-***-metadata',
          credentialStatus: 'ready',
          grantedScopes: [
            'advertiser.read',
            'campaign.read',
            'campaign.write',
            'ads.readonly',
            'ads.validate_only',
          ],
          plaintextCredentialFieldNames: [],
          lastCheckedAt: '2026-07-06T05:44:00.000Z',
        },
        childAccounts: [
          {
            childAccountId: 'demo-tiktok-child-video-001',
            childAccountName: 'HTX TikTok Child Advertiser Demo',
            erpAccountMappingId: 'ERP-ADS-MAP-TIKTOK-001',
            authorizedUnderManager: true,
            approvedForReadOnlyImport: true,
            approvedForFutureProviderActions: true,
            active: true,
            syncStatus: 'fresh',
            lastSyncAt: '2026-07-06T05:32:00.000Z',
            campaigns: [
              {
                campaignId: 'demo-tiktok-campaign-video-001',
                campaignName: 'Local Short Video Monitor Demo',
                channel: 'short_video',
                status: 'ENABLE',
                campaignBudgetEvidence: {
                  campaignBudgetId: 'demo-tiktok-budget-001',
                  campaignBudgetResourceName:
                    'tiktok/demo-tiktok-child-video-001/campaign-budgets/demo-tiktok-budget-001',
                  evidenceSource: 'mock_fixture',
                  lastVerifiedAt: '2026-07-06T05:32:00.000Z',
                },
                erpProductMappingStatus: 'mapped',
                supplierMappingStatus: 'mapped',
                orderProfitMappingStatus: 'mapped',
                cashflowMappingStatus: 'mapped',
                adGroups: [
                  {
                    adGroupId: 'demo-tiktok-adgroup-video-001',
                    adGroupName: 'Video View Demo',
                    erpProductId: 'ERP-PRODUCT-COOKWARE-DEMO',
                    erpProductName: 'Cookware demo product',
                    supplierId: 'ERP-SUPPLIER-SAFE-DEMO',
                    supplierName: 'Safe supplier demo',
                    erpProductMappingStatus: 'mapped',
                    supplierMappingStatus: 'mapped',
                    profitMappingStatus: 'mapped',
                    stockMappingStatus: 'mapped',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    pendingActions: [
      {
        actionId: 'MGR-ACTION-GADS-BUDGET-001',
        actionType: 'update_campaign_budget',
        provider: 'google_ads',
        managerAccountId: 'demo-gads-mcc-htx-001',
        childAccountId: 'demo-gads-child-search-001',
        campaignId: 'demo-gads-campaign-scale-001',
        adGroupId: 'demo-gads-adgroup-cooker-001',
        campaignBudgetId: 'demo-gads-budget-001',
        currentDailyBudgetVnd: 1000000,
        requestedDailyBudgetVnd: 1080000,
        approvalId: 'ADSAPPROVAL-MGR-GADS-BUDGET-001',
        approvalStatus: 'approved',
        validateOnlyReadiness: 'ready',
        preflightReadiness: 'ready',
        auditEvidenceId: 'ADSAUDIT-MGR-GADS-BUDGET-001',
        rollbackPlanId: 'ADSROLLBACK-MGR-GADS-BUDGET-001',
        idempotencyKey: 'mgr:gads:budget:demo:001',
        killSwitchArmed: true,
        businessSafety: {
          cashflowSafe: true,
          grossMarginSafe: true,
          contributionProfitSafe: true,
          stockCoverageSafe: true,
          supplierReliabilitySafe: true,
          fulfillmentCapacitySafe: true,
          refundRiskSafe: true,
          dataFreshnessSafe: true,
          dailyLossLimitSafe: true,
          monthlyLossLimitSafe: true,
        },
        channel: 'search',
      },
      {
        actionId: 'MGR-ACTION-META-PAUSE-001',
        actionType: 'pause_ad_group',
        provider: 'meta_ads',
        managerAccountId: 'demo-meta-bm-htx-001',
        childAccountId: 'demo-meta-child-social-001',
        campaignId: 'demo-meta-campaign-retarget-001',
        adGroupId: 'demo-meta-adset-fan-001',
        campaignBudgetId: 'demo-meta-budget-001',
        approvalId: 'ADSAPPROVAL-MGR-META-PAUSE-001',
        approvalStatus: 'approved',
        validateOnlyReadiness: 'ready',
        preflightReadiness: 'ready',
        auditEvidenceId: 'ADSAUDIT-MGR-META-PAUSE-001',
        rollbackPlanId: 'ADSROLLBACK-MGR-META-PAUSE-001',
        idempotencyKey: 'mgr:meta:pause:demo:001',
        killSwitchArmed: true,
        businessSafety: {
          cashflowSafe: true,
          grossMarginSafe: true,
          contributionProfitSafe: true,
          stockCoverageSafe: true,
          supplierReliabilitySafe: true,
          fulfillmentCapacitySafe: true,
          refundRiskSafe: true,
          dataFreshnessSafe: true,
          dailyLossLimitSafe: true,
          monthlyLossLimitSafe: true,
        },
        channel: 'social_feed',
      },
      {
        actionId: 'MGR-ACTION-TIKTOK-MONITOR-001',
        actionType: 'monitor_only',
        provider: 'tiktok_ads',
        managerAccountId: 'demo-tiktok-bc-htx-001',
        childAccountId: 'demo-tiktok-child-video-001',
        campaignId: 'demo-tiktok-campaign-video-001',
        adGroupId: 'demo-tiktok-adgroup-video-001',
        campaignBudgetId: 'demo-tiktok-budget-001',
        approvalStatus: 'missing',
        validateOnlyReadiness: 'not_required',
        preflightReadiness: 'missing',
        killSwitchArmed: false,
        businessSafety: {
          cashflowSafe: true,
          grossMarginSafe: true,
          contributionProfitSafe: true,
          stockCoverageSafe: true,
          supplierReliabilitySafe: true,
          fulfillmentCapacitySafe: true,
          refundRiskSafe: true,
          dataFreshnessSafe: true,
          dailyLossLimitSafe: true,
          monthlyLossLimitSafe: true,
        },
        channel: 'short_video',
      },
    ],
  };
