import type {
  AdsAutomationGoogleAdsMockImportDemoInput,
} from './contracts/ads-automation-google-ads-mock-import-demo.contract';

export const ADS_AUTOMATION_GOOGLE_ADS_MOCK_IMPORT_DEMO_FIXTURE:
  AdsAutomationGoogleAdsMockImportDemoInput = {
    reportDate: '2026-07-04',
    now: '2026-07-04T05:00:00.000Z',
    importRunId: 'GADS-MOCK-RUN-20260704-001',
    cashflowMode: 'safe',
    accountId: 'HTX-GADS-PRIMARY',
    customerId: '1234567890',
    loginCustomerId: '5555555555',
    accountName: 'HTX Bach Gia - Primary Google Ads',
    sourceTrustLevel: 'fixture_verified',
    googleAdsRows: [
      {
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        loginCustomerId: '5555555555',
        accountName: 'HTX Bach Gia - Primary Google Ads',
        campaignId: '1001',
        campaignName: 'Search - Scale Cooker',
        campaignStatus: 'ENABLED',
        adGroupId: '2001',
        adGroupName: 'Rice cooker winning ad group',
        adGroupStatus: 'ENABLED',
        adId: '5001',
        adName: 'Scale creative A',
        adStatus: 'ENABLED',
        campaignBudgetId: '3001',
        campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
        campaignBudgetAmountVnd: 1000000,
        costVnd: 300000,
        spendVnd: 300000,
        clicks: 120,
        impressions: 5000,
        conversions: 12,
        orders: 12,
        revenueVnd: 4000000,
        grossProfitVnd: 1600000,
        netProfitAfterAdsVnd: 700000,
        returnRatePercent: 8,
        dataQualityScore: 0.92,
        reportDate: '2026-07-04',
        lastSuccessfulSyncAt: '2026-07-04T04:00:00.000Z',
        importRunId: 'GADS-MOCK-RUN-20260704-001',
        sourceTrustLevel: 'fixture_verified',
        mappedProductIds: ['P_SCALE'],
      },
      {
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        loginCustomerId: '5555555555',
        accountName: 'HTX Bach Gia - Primary Google Ads',
        campaignId: '1002',
        campaignName: 'Search - Refund Heavy',
        campaignStatus: 'ENABLED',
        adGroupId: '2002',
        adGroupName: 'Refund-heavy ad group',
        adGroupStatus: 'ENABLED',
        adId: '5002',
        adName: 'Refund creative B',
        adStatus: 'ENABLED',
        campaignBudgetId: '3002',
        campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3002',
        campaignBudgetAmountVnd: 500000,
        costVnd: 350000,
        spendVnd: 350000,
        clicks: 88,
        impressions: 4100,
        conversions: 0,
        orders: 0,
        revenueVnd: 0,
        grossProfitVnd: 0,
        netProfitAfterAdsVnd: -350000,
        returnRatePercent: 40,
        dataQualityScore: 0.88,
        reportDate: '2026-07-04',
        lastSuccessfulSyncAt: '2026-07-04T04:00:00.000Z',
        importRunId: 'GADS-MOCK-RUN-20260704-001',
        sourceTrustLevel: 'fixture_verified',
        mappedProductIds: ['P_BAD'],
      },
    ],
    products: [
      {
        productId: 'P_SCALE',
        sku: 'SKU-SCALE',
        name: 'Profitable cooker',
        netProfitVnd: 1250000,
        adAttributedNetProfitAfterAdsVnd: 700000,
        marginPercent: 45,
        returnCancelRefundRatePercent: 8,
        stockAvailable: 120,
        reservedQuantity: 8,
        incomingQuantity: 50,
        daysOfCover: 20,
        mediaReady: true,
        landingReady: true,
        offerReady: true,
        mappedAdGroupIds: ['2001'],
        supplierIds: ['SUP_SAFE'],
        fulfillmentCapacityStatus: 'available',
        cashConversionStatus: 'safe',
      },
      {
        productId: 'P_BAD',
        sku: 'SKU-BAD',
        name: 'Refund-heavy set',
        netProfitVnd: -450000,
        adAttributedNetProfitAfterAdsVnd: -350000,
        marginPercent: -5,
        returnCancelRefundRatePercent: 40,
        stockAvailable: 50,
        reservedQuantity: 4,
        incomingQuantity: 0,
        daysOfCover: 12,
        mediaReady: true,
        landingReady: true,
        offerReady: true,
        mappedAdGroupIds: ['2002'],
        supplierIds: ['SUP_WEAK_1', 'SUP_WEAK_2'],
        fulfillmentCapacityStatus: 'constrained',
        cashConversionStatus: 'unsafe',
      },
    ],
    suppliers: [
      {
        productId: 'P_SCALE',
        supplierId: 'SUP_SAFE',
        supplierName: 'Safe Supplier',
        quoteApproved: true,
        currentQuoteVnd: 180000,
        priorQuoteVnd: 185000,
        marginAfterCostPercent: 42,
        leadTimeDays: 4,
        lateDeliveryRatePercent: 3,
        paymentFreshnessDays: 5,
        capacityStatus: 'available',
        returnFaultRatePercent: 2,
      },
      {
        productId: 'P_BAD',
        supplierId: 'SUP_WEAK_1',
        supplierName: 'Weak Supplier 1',
        quoteApproved: true,
        currentQuoteVnd: 260000,
        priorQuoteVnd: 230000,
        marginAfterCostPercent: 8,
        leadTimeDays: 14,
        lateDeliveryRatePercent: 20,
        paymentFreshnessDays: 45,
        capacityStatus: 'constrained',
        returnFaultRatePercent: 14,
      },
      {
        productId: 'P_BAD',
        supplierId: 'SUP_WEAK_2',
        supplierName: 'Weak Supplier 2',
        quoteApproved: false,
        currentQuoteVnd: 280000,
        priorQuoteVnd: 250000,
        marginAfterCostPercent: -2,
        leadTimeDays: 16,
        lateDeliveryRatePercent: 22,
        paymentFreshnessDays: 60,
        capacityStatus: 'blocked',
        returnFaultRatePercent: 18,
      },
    ],
    orderProfitRows: [
      {
        orderId: 'ORDER-SCALE-001',
        productId: 'P_SCALE',
        supplierId: 'SUP_SAFE',
        adGroupId: '2001',
        quantity: 12,
        revenueVnd: 4000000,
        grossProfitVnd: 1600000,
        netProfitVnd: 1250000,
        cashCollectedVnd: 4000000,
        cashConversionDays: 2,
        refundRiskPercent: 8,
      },
      {
        orderId: 'ORDER-BAD-001',
        productId: 'P_BAD',
        supplierId: 'SUP_WEAK_1',
        adGroupId: '2002',
        quantity: 1,
        revenueVnd: 0,
        grossProfitVnd: 0,
        netProfitVnd: -450000,
        cashCollectedVnd: 0,
        cashConversionDays: 30,
        refundRiskPercent: 40,
      },
    ],
    policy: {
      availableAdsCashVnd: 500000,
      cashflowGatePassed: true,
      maxBudgetIncreasePercent: 20,
      mediumConfidenceIncreasePercent: 10,
      minOrdersForScale: 5,
      minDataQualityScore: 0.75,
      minSpendForPauseVnd: 200000,
      maxReturnRatePercent: 25,
      minMarginPercent: 20,
      minStockAvailable: 10,
      minDaysOfCover: 7,
      maxSupplierLeadTimeDays: 10,
      maxSupplierLateDeliveryRatePercent: 15,
      maxSupplierReturnFaultRatePercent: 12,
      maxSupplierPaymentFreshnessDays: 30,
    },
  };
