import type { AdsAutomationPolicyDecisionAuditLinkageInput } from './contracts/ads-automation-policy-decision-audit-linkage.contract';
import { AdsAutomationMonitoringIncidentReadinessService } from './ads-automation-monitoring-incident-readiness.service';
import { ADS_AUTOMATION_MONITORING_INCIDENT_READINESS_FIXTURE } from './ads-automation-monitoring-incident-readiness.fixture';

const approvalId = 'ADSAPPROVAL-ads_policy_linkage_demo_budget';
const executionRecordId = 'ADSEXEC-DRYRUN-ads_policy_linkage_demo_budget-REQ-DEMO';
const validationId = 'ADSPROVIDERVALIDATE-ads_policy_linkage_demo_budget';
const policyDecisionId = 'ADSPOLICY-ads_policy_linkage_demo_budget';
const pendingActionId = 'ADSPENDINGACTION-ads_policy_linkage_demo_budget';
const auditId = 'ADSAUDIT-ads_policy_linkage_demo_budget-approve-REQ-DEMO';

export const ADS_AUTOMATION_POLICY_DECISION_AUDIT_LINKAGE_FIXTURE:
  AdsAutomationPolicyDecisionAuditLinkageInput = {
    approvalId,
    reportDate: '2026-07-04',
    approvalEvidenceIndex: {
      schemaVersion: 'ads_automation_approval_evidence_index.v1',
      generatedAt: '2026-07-04T06:45:00.000Z',
      query: { approval_id: approvalId },
      safety: {
        read_only: true,
        dry_run: true,
        in_memory_only: false,
        persistence_used: true,
        durable_storage_used: true,
        erp_local_persistence_used: true,
        provider_persistence_used: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        erp_mutation_used: false,
        payment_mutation_used: false,
        production_ready: false,
        approval_required_for_all_records: true,
        future_live_execution_allowed: false,
        execution_allowed_now: false,
        live_path_implemented: false,
        provider_mutation_used: false,
        direct_google_ads_api_call: false,
        approval_evidence_index_readback: true,
        approval_evidence_index_persistence_performed: false,
        validateOnly_evidence_persistence_performed: false,
        policy_decision_evidence_persistence_performed: false,
        preflight_persistence_performed: false,
      },
      summary: {} as any,
      links: {
        execution_record_ids: [executionRecordId],
        validateOnly_validation_ids_from_preflight: [validationId],
        validateOnly_validation_ids_with_evidence: [validationId],
        validateOnly_validation_ids_missing_evidence: [],
        policy_decision_ids_from_preflight: [policyDecisionId],
        policy_decision_ids_with_evidence: [policyDecisionId],
        policy_decision_ids_missing_evidence: [],
      },
      pendingApproval: null,
      pendingActionReviewEvidence: [],
      sourceSyncDecisionEvidence: [],
      sourceSyncDecisionGates: null,
      validateOnlyEvidenceRecords: [{
        schemaVersion: 'ads_automation_validate_only_evidence.v1',
        validation_id: validationId,
        idempotency_key: 'ads-validate-only-evidence:demo:budget',
        validateOnly_evidence_persisted: true,
        pending_action_id: pendingActionId,
        approval_id: approvalId,
        source_pending_action_status: 'pending_validation',
        action_type: 'update_campaign_budget',
        action_family: 'provider_google_ads',
        provider: 'google',
        resource_type: 'campaign_budget',
        entity_type: 'ad_group',
        entity_id: '2001',
        customerId: '1234567890',
        campaignId: '1001',
        adGroupId: '2001',
        campaignBudgetId: '3001',
        campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
        requested_change: {
          action_type: 'update_campaign_budget',
          customerId: '1234567890',
          campaignId: '1001',
          adGroupId: '2001',
          campaignBudgetId: '3001',
          currentBudgetVnd: 1000000,
          dailyBudget: 1200000,
          rollbackPlan: 'Restore previous campaign budget from ERP synced read model.',
        },
        status: 'validate_only_passed',
        providerValidationStatus: 'provider_validate_passed',
        providerRequestId: 'REQ-DEMO-MOCK-VALIDATE',
        providerValidatedAt: '2026-07-04T06:10:00.000Z',
        providerValidationErrors: [],
        before_state_snapshot: {
          snapshot_status: 'mocked_boundary_snapshot',
          required_before_future_execution: true,
          source: 'erp_synced_google_ads_read_model',
          customerId: '1234567890',
          campaignId: '1001',
          adGroupId: '2001',
          campaignBudgetId: '3001',
          campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
          snapshot: {
            status: 'ENABLED',
            currentDailyBudgetVnd: 1000000,
            syncedAt: '2026-07-04T06:05:00.000Z',
          },
        },
        provider_boundary_evidence: {
          boundary_mode: 'erp_local_mock_only',
          status_source: 'mock_provider_result',
          mocked_provider_result_used: true,
          provider_api_called: false,
          google_ads_api_called: false,
          validateOnly_called: false,
          direct_google_ads_api_call: false,
          operation_builder_called: false,
          raw_provider_request_included: false,
          evidence: ['Fixture uses mocked validate-only evidence only.'],
        },
        blockers: [],
        approval_can_be_considered_executable: true,
        executable_now: false,
        execution_allowed_now: false,
        validate_only_required_before_execution: true,
        next_required_action: 'continue_human_approval_flow',
        source_pending_action: {
          pending_action_id: pendingActionId,
          source_decision_id: 'DEC-scale_amount-2001',
        } as any,
        future_live_execution_allowed: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        erp_mutation_used: false,
        payment_mutation_used: false,
        direct_google_ads_api_call: false,
        provider_mutation_used: false,
        live_path_implemented: false,
        persistence_used: true,
        durable_storage_used: true,
        erp_local_persistence_used: true,
        provider_persistence_used: false,
        storage: 'erp_local_mongo',
        requestedByUserId: 'director-1',
        requestedByRole: 'director',
        requestId: 'REQ-DEMO',
        createdAt: '2026-07-04T06:10:00.000Z',
        persistedAt: '2026-07-04T06:10:00.000Z',
      } as any],
      policyDecisionEvidenceRecords: [{
        schemaVersion: 'ads_automation_execution_policy_decision_evidence.v1',
        policy_decision_id: policyDecisionId,
        idempotency_key: 'ads-policy-decision:demo:budget',
        approval_id: approvalId,
        policy_allowed: true,
        policy_source: 'erp_loss_limit_spend_cap_policy',
        blockers: [],
        evaluatedAt: '2026-07-04T06:12:00.000Z',
        policy_decision_record_persisted: true,
        future_live_execution_allowed: false,
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        erp_mutation_used: false,
        payment_mutation_used: false,
        direct_google_ads_api_call: false,
        provider_mutation_used: false,
        live_path_implemented: false,
        persistence_used: true,
        durable_storage_used: true,
        erp_local_persistence_used: true,
        provider_persistence_used: false,
        storage: 'erp_local_mongo',
        requestedByUserId: 'director-1',
        requestedByRole: 'director',
        requestId: 'REQ-DEMO',
        createdAt: '2026-07-04T06:12:00.000Z',
        persistedAt: '2026-07-04T06:12:00.000Z',
      }],
      executionPreflightDryRunRecords: [{
        execution_record_id: executionRecordId,
        idempotency_key: 'ads-execution-preflight:demo:budget:REQ-DEMO',
        approval_id: approvalId,
        source_draft_id: 'ADSDRAFT-20260704-update_campaign_budget-2001',
        source_decision_id: 'DEC-scale_amount-2001',
        action_type: 'update_campaign_budget',
        action_family: 'provider_google_ads',
        provider: 'google',
        resource_type: 'campaign_budget',
        entity_type: 'ad_group',
        entity_id: '2001',
        accountId: '1234567890',
        platform: 'google',
        approval_status: 'approved',
        approval_decision_audit_id: 'ADSAUDIT-DEMO-approve',
        approval_decision_audit_persisted: true,
        source_readiness_safe: true,
        kill_switch_active: false,
        kill_switch_reason: null,
        validateOnly_validation_id: validationId,
        validateOnly_evidence_persisted: true,
        validateOnly_status: 'validate_only_passed',
        policy_decision_id: policyDecisionId,
        policy_decision_evidence_persisted: true,
        policy_allowed: true,
        google_ads_production_enabled: false,
        preflight_status: 'blocked_before_future_live_execution',
        dry_run_record_status: 'recorded_local_only',
        future_live_execution_allowed: false,
        execution_allowed_now: false,
        provider_api_called: false,
        google_ads_api_called: false,
        validateOnly_called: false,
        live_ads_execution_used: false,
        erp_mutation_used: false,
        payment_mutation_used: false,
        direct_google_ads_api_call: false,
        provider_mutation_used: false,
        live_path_implemented: false,
        campaignBudgetId_fallback_used: false,
        preflight_record_persisted: true,
        persistence_used: true,
        durable_storage_used: true,
        erp_local_persistence_used: true,
        provider_persistence_used: false,
        storage: 'erp_local_mongo',
        requested_change: {
          action_type: 'update_campaign_budget',
          currentBudgetVnd: 1000000,
          dailyBudget: 1200000,
        },
        identifiers: {
          customerId: '1234567890',
          campaignId: '1001',
          adGroupId: '2001',
          campaignBudgetId: '3001',
          campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
        },
        gates: [],
        blockers: ['GOOGLE_ADS_PRODUCTION_ENABLED', 'live_path_not_implemented'],
        next_required_action: 'future_executor_not_implemented',
        source_pending_approval: {
          approval_id: approvalId,
          source_decision_id: 'DEC-scale_amount-2001',
          status: 'approved',
          idempotency_key: 'ads-draft:demo:budget',
          typedPayload: {
            customerId: '1234567890',
            campaignId: '1001',
            adGroupId: '2001',
            campaignBudgetId: '3001',
            currentBudgetVnd: 1000000,
            dailyBudget: 1200000,
          },
          source_evidence_references: [{
            decision_id: 'DEC-scale_amount-2001',
            rollback_plan: 'Restore previous campaign budget from ERP synced read model.',
          }],
          sourceSyncDecisionEvidence: [
            'google_ads',
            'advertising_costs',
            'product_mapping',
            'inventory_profit',
            'supplier_safety',
          ].map((sourceKey) => ({
            sourceKey,
            reportDate: '2026-07-04',
            freshnessStatus: 'fresh',
            coverageStatus: 'covered',
            lastSuccessfulSyncAt: '2026-07-04T06:00:00.000Z',
            latestRecordDate: '2026-07-04',
            blockingReason: null,
            blockingReasons: [],
            canUseForAdsAutomationDecision: true,
          })),
          sourceSyncDecisionGates: {
            canGenerateActionDraft: true,
            canUseGoogleAdsDataClaim: true,
            canExecuteLive: false,
          },
        } as any,
        source_validateOnly_plan: {
          validation_id: validationId,
          pending_action_id: pendingActionId,
          approval_id: approvalId,
          source_pending_action_status: 'pending_validation',
          action_type: 'update_campaign_budget',
          action_family: 'provider_google_ads',
          provider: 'google',
          resource_type: 'campaign_budget',
          entity_type: 'ad_group',
          entity_id: '2001',
          customerId: '1234567890',
          campaignId: '1001',
          adGroupId: '2001',
          campaignBudgetId: '3001',
          campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
          requested_change: {
            action_type: 'update_campaign_budget',
            customerId: '1234567890',
            campaignId: '1001',
            adGroupId: '2001',
            campaignBudgetId: '3001',
            currentBudgetVnd: 1000000,
            dailyBudget: 1200000,
            rollbackPlan: 'Restore previous campaign budget from ERP synced read model.',
          },
          status: 'validate_only_passed',
          providerValidationStatus: 'provider_validate_passed',
          providerRequestId: 'REQ-DEMO-MOCK-VALIDATE',
          providerValidatedAt: '2026-07-04T06:10:00.000Z',
          providerValidationErrors: [],
          before_state_snapshot: {
            snapshot_status: 'mocked_boundary_snapshot',
            required_before_future_execution: true,
            source: 'erp_synced_google_ads_read_model',
            customerId: '1234567890',
            campaignId: '1001',
            adGroupId: '2001',
            campaignBudgetId: '3001',
            campaignBudgetResourceName: 'customers/1234567890/campaignBudgets/3001',
            snapshot: {
              status: 'ENABLED',
              currentDailyBudgetVnd: 1000000,
              syncedAt: '2026-07-04T06:05:00.000Z',
            },
          },
          provider_boundary_evidence: {
            boundary_mode: 'erp_local_mock_only',
            status_source: 'mock_provider_result',
            mocked_provider_result_used: true,
            provider_api_called: false,
            google_ads_api_called: false,
            validateOnly_called: false,
            direct_google_ads_api_call: false,
            operation_builder_called: false,
            raw_provider_request_included: false,
            evidence: ['Fixture uses mocked validate-only evidence only.'],
          },
          blockers: [],
          approval_can_be_considered_executable: true,
          executable_now: false,
          execution_allowed_now: false,
          validate_only_required_before_execution: true,
          next_required_action: 'continue_human_approval_flow',
          source_pending_action: {
            pending_action_id: pendingActionId,
            source_decision_id: 'DEC-scale_amount-2001',
          } as any,
        } as any,
        policy_decision: null,
        requestedByUserId: 'director-1',
        requestedByRole: 'director',
        requestId: 'REQ-DEMO',
        createdAt: '2026-07-04T06:20:00.000Z',
        persistedAt: '2026-07-04T06:20:00.000Z',
      } as any],
    },
    auditRecords: [{
      schemaVersion: 'ads_automation_decision_draft_approval_decision_audit_record.v1',
      audit_id: auditId,
      idempotency_key: 'ads-decision-audit:demo:budget:REQ-DEMO',
      approval_id: approvalId,
      source_draft_id: 'ADSDRAFT-20260704-update_campaign_budget-2001',
      source_decision_id: 'DEC-scale_amount-2001',
      action_type: 'update_campaign_budget',
      action_family: 'provider_google_ads',
      provider: 'google',
      resource_type: 'campaign_budget',
      entity_type: 'ad_group',
      entity_id: '2001',
      accountId: '1234567890',
      productId: 'P_SCALE',
      supplierId: null,
      platform: 'google',
      previous_status: 'pending_approval',
      proposed_status: 'approved',
      decision: 'approve',
      reviewerUserId: 'director-1',
      reviewerRole: 'director',
      reason: 'Director approved local policy evidence for dry-run preflight only.',
      requestId: 'REQ-DEMO',
      validation_status: 'eligible_for_human_decision',
      prerequisites_valid: 12,
      prerequisites_blocked: 0,
      blockers: [],
      prerequisites: [],
      pending_approval_snapshot: {} as any,
      audit_record_persisted: true,
      status_change_performed: true,
      provider_api_called: false,
      google_ads_api_called: false,
      validateOnly_called: false,
      live_ads_execution_used: false,
      erp_mutation_used: false,
      payment_mutation_used: false,
      execution_allowed_now: false,
      persistence_used: true,
      durable_storage_used: true,
      erp_local_persistence_used: true,
      provider_persistence_used: false,
      storage: 'erp_local_mongo',
      source_preview_createdAt: '2026-07-04T06:15:00.000Z',
      createdAt: '2026-07-04T06:15:00.000Z',
      persistedAt: '2026-07-04T06:15:00.000Z',
    }],
    lossLimitPolicy: {
      schemaVersion: 'ads_automation_loss_limit_policy.v1',
      generatedAt: '2026-07-04T06:18:00.000Z',
      reportDate: '2026-07-04',
      safety: {} as any,
      summary: {
        status: 'ready_for_local_review',
        fixture_mode: 'custom_local_payload',
        requested_action_type: 'update_campaign_budget',
        requested_action_mode: 'scale_up',
        policy_allowed_for_requested_action: true,
        all_safe_for_increase: true,
        scale_up_execution_mode: 'pending_validation',
        human_approval_required: true,
        human_approval_present: true,
        emergency_stop_active: false,
        daily_loss_limit_safe: true,
        monthly_loss_limit_safe: true,
        spend_caps_safe: true,
        gross_margin_safe: true,
        contribution_profit_safe: true,
        cash_conversion_working_capital_safe: true,
        stock_coverage_safe: true,
        supplier_reliability_safe: true,
        fulfillment_capacity_safe: true,
        return_refund_risk_safe: true,
        data_freshness_safe: true,
        campaignBudgetId_missing: false,
        safe_reduction_or_pause_available: true,
        provider_api_called: false,
        google_ads_api_called: false,
        live_ads_execution_used: false,
        execution_allowed_now: false,
        production_ready: false,
        next_required_action: 'review_local_loss_limit_policy_evidence',
      },
      action: {} as any,
      approval: {} as any,
      checks: [],
      spendCapDecisions: [],
      economicsDecisions: [],
      scaleBlockers: [],
      requestedActionBlockers: [],
      safeActionsAvailable: ['monitor_only'],
      markdownPreview: 'Local fixture only.',
    },
    monitoringReadiness: new AdsAutomationMonitoringIncidentReadinessService()
      .build(ADS_AUTOMATION_MONITORING_INCIDENT_READINESS_FIXTURE),
  };
