import type {
  AdsAutomationMonitoringIncidentReadinessInput,
} from './contracts/ads-automation-monitoring-incident-readiness.contract';
import { AdsAutomationMonitoringTelemetryReadModelService } from './ads-automation-monitoring-telemetry-read-model.service';
import {
  ADS_AUTOMATION_MONITORING_TELEMETRY_READ_MODEL_FIXTURE,
} from './ads-automation-monitoring-telemetry-read-model.fixture';

export const ADS_AUTOMATION_MONITORING_INCIDENT_READINESS_FIXTURE:
  AdsAutomationMonitoringIncidentReadinessInput = {
    reportDate: '2026-07-04',
    now: '2026-07-04T06:45:00.000Z',
    fixtureMode: 'htx_ads_monitoring_incident_demo',
    telemetryReadModel: new AdsAutomationMonitoringTelemetryReadModelService()
      .build(ADS_AUTOMATION_MONITORING_TELEMETRY_READ_MODEL_FIXTURE),
    providerRateLimits: [{
      provider: 'google_ads',
      accountId: 'HTX-GADS-PRIMARY',
      customerId: '1234567890',
      windowStartedAt: '2026-07-04T06:00:00.000Z',
      windowEndsAt: '2026-07-04T07:00:00.000Z',
      requestsUsed: 320,
      requestsLimit: 1000,
      minRemainingRequests: 200,
      throttlingActive: false,
      cooldownEndsAt: null,
      source: 'fixture',
    }],
    spendRateMonitors: [
      {
        scope: 'account',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        spendLastHourVnd: 180000,
        spendTodayVnd: 2600000,
        spendMonthVnd: 42000000,
        hourlySpendCapVnd: 500000,
        dailyBudgetVnd: 5000000,
        monthlyBudgetVnd: 100000000,
        dailyBurnAlertPercent: 90,
        monthlyBurnAlertPercent: 90,
      },
      {
        scope: 'ad_group',
        accountId: 'HTX-GADS-PRIMARY',
        customerId: '1234567890',
        campaignId: '1001',
        adGroupId: '2001',
        campaignBudgetId: '3001',
        spendLastHourVnd: 90000,
        spendTodayVnd: 720000,
        spendMonthVnd: 12800000,
        hourlySpendCapVnd: 250000,
        dailyBudgetVnd: 1200000,
        monthlyBudgetVnd: 30000000,
        dailyBurnAlertPercent: 90,
        monthlyBurnAlertPercent: 90,
      },
    ],
    providerErrorRateMonitors: [{
      provider: 'google_ads',
      accountId: 'HTX-GADS-PRIMARY',
      customerId: '1234567890',
      windowMinutes: 60,
      requestCount: 320,
      errorCount: 2,
      timeoutCount: 1,
      rateLimitErrorCount: 0,
      maxErrorRatePercent: 3,
      maxTimeoutRatePercent: 2,
    }],
    staleImportAlerts: [{
      alertId: 'ADSALERT-import-google-ads-fresh',
      sourceKey: 'google_ads',
      accountId: 'HTX-GADS-PRIMARY',
      severity: 'info',
      status: 'resolved',
      freshnessStatus: 'fresh',
      lastSuccessfulSyncAt: '2026-07-04T06:35:00.000Z',
      maxAgeMinutes: 120,
      ageMinutes: 10,
      blocking: false,
    }],
    validateOnlyPreflightAlerts: [],
    incidents: [{
      incidentId: 'ADSINC-monitoring-green-20260704',
      severity: 'info',
      status: 'resolved',
      startedAt: '2026-07-04T05:00:00.000Z',
      resolvedAt: '2026-07-04T05:10:00.000Z',
      affectedScope: 'google_ads:HTX-GADS-PRIMARY',
      summary: 'Resolved fixture incident proving incident evidence shape.',
      blockingScaleUp: false,
      linkedAlertIds: [],
    }],
    operatorAcknowledgements: [],
  };
