import { ThresholdSourceRecord } from './threshold-source.contract';

export const THRESHOLD_SOURCE_RECORDS_TOKEN = 'AI_DATA_PACK_THRESHOLD_SOURCE_RECORDS';

const EFFECTIVE_FROM = '2026-01-01';
const REVIEWED_AT = '2026-06-14T00:00:00.000Z';

export const THRESHOLD_SOURCE_RECORDS: readonly ThresholdSourceRecord[] = [
  {
    threshold_key: 'low_inventory.days_of_cover_threshold',
    finding_key: 'low_inventory_best_seller',
    business_owner: 'operations',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'low_inventory.days_of_cover_threshold',
    value_type: 'days',
    unit: 'days',
    value: 7,
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_mutate_inventory; do_not_execute_replenishment',
    semantic_notes: ['Preserves existing implicit 7 day cover threshold as read-only repo config metadata.'],
  },
  {
    threshold_key: 'low_inventory.sales_velocity_window',
    finding_key: 'low_inventory_best_seller',
    business_owner: 'operations',
    source_type: 'derived_candidate',
    source_module_or_collection: 'ordertest2',
    field_path_or_config_key: 'orders.orderDate_or_updatedAt_window',
    value_type: 'formula',
    unit: 'order_window',
    value: 'observed_positive_quantity_order_window',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_mutate_inventory; do_not_execute_replenishment',
    semantic_notes: ['Sales velocity remains derived from observed active order quantity and timestamps.'],
  },
  {
    threshold_key: 'low_inventory.bestseller_rank_window',
    finding_key: 'low_inventory_best_seller',
    business_owner: 'operations',
    source_type: 'derived_candidate',
    source_module_or_collection: 'ordertest2',
    field_path_or_config_key: 'orders.quantity_rank',
    value_type: 'formula',
    unit: 'rank',
    value: 'rank_by_recent_order_quantity_then_order_count',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_mutate_inventory; do_not_execute_replenishment',
    semantic_notes: ['Bestseller rank remains derived and is not an action trigger.'],
  },
  {
    threshold_key: 'low_inventory.reorder_point',
    finding_key: 'low_inventory_best_seller',
    business_owner: 'operations',
    source_type: 'schema_field',
    source_module_or_collection: 'products',
    field_path_or_config_key: 'products.minStock',
    value_type: 'number',
    unit: 'quantity',
    value: 'products.minStock',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_mutate_inventory; do_not_execute_replenishment',
    semantic_notes: ['Uses existing product minimum stock field as read-only threshold source metadata.'],
  },
  {
    threshold_key: 'supplier_cost.cost_increase_percent_threshold',
    finding_key: 'supplier_cost_up',
    business_owner: 'procurement',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'supplier_cost.cost_increase_percent_threshold',
    value_type: 'percent',
    unit: 'percent',
    value: 15,
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_change_prices; do_not_create_supplier_actions; do_not_mutate_dealer_prices; do_not_create_purchase_order; do_not_execute_ads_actions',
    semantic_notes: ['Preserves existing implicit 15 percent supplier cost increase threshold.'],
  },
  {
    threshold_key: 'supplier_cost.supplier_quote_effective_date',
    finding_key: 'supplier_cost_up',
    business_owner: 'procurement',
    source_type: 'schema_field',
    source_module_or_collection: 'supplierquotes',
    field_path_or_config_key: 'supplierquotes.effectiveAt_or_createdAt',
    value_type: 'date',
    unit: 'date',
    value: 'supplier quote effective timestamp ordering',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_change_prices; do_not_create_supplier_actions; do_not_mutate_dealer_prices; do_not_create_purchase_order; do_not_execute_ads_actions',
    semantic_notes: ['Quote effective date ordering remains read-only evidence.'],
  },
  {
    threshold_key: 'supplier_cost.dealer_price_lag_threshold',
    finding_key: 'supplier_cost_up',
    business_owner: 'pricing',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'supplier_cost.dealer_price_lag_threshold',
    value_type: 'formula',
    unit: 'days',
    value: 'dealer price date older than supplier quote date',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'emit_with_downgrade',
    not_allowed_actions: 'do_not_change_prices; do_not_create_supplier_actions; do_not_mutate_dealer_prices; do_not_create_purchase_order; do_not_execute_ads_actions',
    semantic_notes: ['Dealer price lag is advisory context only and does not authorize price changes.'],
  },
  {
    threshold_key: 'dealer_receivable.settlement_due_date_source',
    finding_key: 'overdue_dealer_receivables',
    business_owner: 'finance',
    source_type: 'schema_field',
    source_module_or_collection: 'ordertest2',
    field_path_or_config_key: 'ordertest2.agentPaymentDueDate',
    value_type: 'date',
    unit: 'date',
    value: 'agentPaymentDueDate before report date',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_collection_action; do_not_block_agent; do_not_mutate_customer; do_not_mutate_invoice_or_order; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Settlement due date is evidence only; finance terminology remains advisory.'],
  },
  {
    threshold_key: 'dealer_receivable.outstanding_balance_formula',
    finding_key: 'overdue_dealer_receivables',
    business_owner: 'finance',
    source_type: 'derived_candidate',
    source_module_or_collection: 'ordertest2',
    field_path_or_config_key: 'agent payment amount formula',
    value_type: 'formula',
    unit: 'VND',
    value: 'positive pending agent settlement balance',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_collection_action; do_not_block_agent; do_not_mutate_customer; do_not_mutate_invoice_or_order; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Balance formula is still settlement pressure evidence, not a collection command.'],
  },
  {
    threshold_key: 'dealer_receivable.overdue_aging_buckets',
    finding_key: 'overdue_dealer_receivables',
    business_owner: 'finance',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'dealer_receivable.overdue_aging_buckets',
    value_type: 'status_set',
    unit: 'days',
    value: ['1_7', '8_14', '15_30', '31_plus'],
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'emit_with_downgrade',
    not_allowed_actions: 'do_not_create_collection_action; do_not_block_agent; do_not_mutate_customer; do_not_mutate_invoice_or_order; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Aging buckets are labels for Director review only.'],
  },
  {
    threshold_key: 'labor.overtime_hours_threshold',
    finding_key: 'labor_overtime_high',
    business_owner: 'hr_operations',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'labor.overtime_hours_threshold',
    value_type: 'hours',
    unit: 'hours_per_day',
    value: 8,
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'low_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_change_staffing; do_not_create_schedule_action; do_not_mutate_payroll; do_not_mutate_timesheets; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Preserves existing implicit 8 hours per employee day threshold.'],
  },
  {
    threshold_key: 'labor.work_hour_source_hierarchy',
    finding_key: 'labor_overtime_high',
    business_owner: 'hr_operations',
    source_type: 'schema_field',
    source_module_or_collection: 'laborcost1',
    field_path_or_config_key: 'laborcost1.workHours',
    value_type: 'formula',
    unit: 'hours',
    value: 'laborcost1.workHours primary source',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'low_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_change_staffing; do_not_create_schedule_action; do_not_mutate_payroll; do_not_mutate_timesheets; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Work hour source is present but remains a weak staffing signal without SLA and capacity mapping.'],
  },
  {
    threshold_key: 'labor.revenue_workload_window',
    finding_key: 'labor_overtime_high',
    business_owner: 'operations',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'labor.revenue_workload_window',
    value_type: 'days',
    unit: 'days',
    value: 7,
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'low_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_change_staffing; do_not_create_schedule_action; do_not_mutate_payroll; do_not_mutate_timesheets; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Preserves existing adjacent 7 day current/prior comparison windows.'],
  },
  {
    threshold_key: 'labor.overtime_growth_threshold',
    finding_key: 'labor_overtime_high',
    business_owner: 'operations',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'labor.overtime_growth_threshold',
    value_type: 'formula',
    unit: 'percent_delta',
    value: 'overtime_growth_percent greater than revenue_growth_percent',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'low_ceiling',
    fallback_behavior: 'emit_with_downgrade',
    not_allowed_actions: 'do_not_change_staffing; do_not_create_schedule_action; do_not_mutate_payroll; do_not_mutate_timesheets; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Growth comparison is advisory and cannot change staffing or payroll.'],
  },
  {
    threshold_key: 'slow_supplier.cost_advantage_threshold',
    finding_key: 'slow_supplier_good_cost',
    business_owner: 'procurement',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'slow_supplier.cost_advantage_threshold',
    value_type: 'percent',
    unit: 'percent',
    value: 5,
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_change_supplier_order; do_not_mutate_inventory; do_not_mutate_stock; do_not_mutate_supplier_cost; do_not_mutate_price; do_not_mutate_cogs; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Preserves existing implicit 5 percent cost advantage threshold.'],
  },
  {
    threshold_key: 'slow_supplier.peer_quote_comparison_method',
    finding_key: 'slow_supplier_good_cost',
    business_owner: 'procurement',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'slow_supplier.peer_quote_comparison_method',
    value_type: 'formula',
    unit: 'same_product_currency_peer_median',
    value: 'latest peer supplier quote median for same product and currency',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_change_supplier_order; do_not_mutate_inventory; do_not_mutate_stock; do_not_mutate_supplier_cost; do_not_mutate_price; do_not_mutate_cogs; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Peer quote comparison is a read-only cost context.'],
  },
  {
    threshold_key: 'slow_supplier.delivery_delay_threshold',
    finding_key: 'slow_supplier_good_cost',
    business_owner: 'procurement',
    source_type: 'repo_config',
    source_module_or_collection: 'threshold_registry_config',
    field_path_or_config_key: 'slow_supplier.delivery_delay_threshold',
    value_type: 'days',
    unit: 'days',
    value: 0,
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'no_row',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_change_supplier_order; do_not_mutate_inventory; do_not_mutate_stock; do_not_mutate_supplier_cost; do_not_mutate_price; do_not_mutate_cogs; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Any positive delivery delay remains advisory procurement evidence.'],
  },
  {
    threshold_key: 'slow_supplier.expected_lead_time_source',
    finding_key: 'slow_supplier_good_cost',
    business_owner: 'procurement',
    source_type: 'schema_field',
    source_module_or_collection: 'products',
    field_path_or_config_key: 'products.estimatedDeliveryDays',
    value_type: 'days',
    unit: 'days',
    value: 'products.estimatedDeliveryDays',
    default_allowed: false,
    effective_from: EFFECTIVE_FROM,
    effective_to: null,
    approval_status: 'approved',
    last_reviewed_at: REVIEWED_AT,
    data_quality_status_impact: 'partial',
    confidence_impact: 'medium_ceiling',
    fallback_behavior: 'emit_with_downgrade',
    not_allowed_actions: 'do_not_create_purchase_order; do_not_change_supplier_order; do_not_mutate_inventory; do_not_mutate_stock; do_not_mutate_supplier_cost; do_not_mutate_price; do_not_mutate_cogs; do_not_mutate_orders_or_revenue; do_not_mutate_cashflow; do_not_execute_ads_actions',
    semantic_notes: ['Product estimated delivery days remains a source indicator, not a supplier action trigger.'],
  },
];
