import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type CapitalAllocationSnapshotDocument = HydratedDocument<CapitalAllocationSnapshot>;

/**
 * Snapshot phân bổ vốn theo ngày
 * Tính toán từ lợi nhuận thuần thực tế
 */
@Schema({ collection: 'capital_allocation_snapshots', timestamps: true })
export class CapitalAllocationSnapshot {
  @Prop({ type: Date, required: true, index: true })
  date: Date;

  @Prop({ type: String, required: true })
  policyName: string; // Reference to policy used

  // ========== NGUỒN VỐN ==========
  @Prop({ type: Number, required: true })
  totalNetProfit: number; // Tổng lợi nhuận thuần tích lũy

  // ========== PHÂN BỔ (Số tiền) ==========
  @Prop({ type: Number, required: true })
  reinvestmentAmount: number; // Tái đầu tư / Ads

  @Prop({ type: Number, required: true })
  safetyReserveAmount: number; // Dự phòng an toàn

  @Prop({ type: Number, required: true })
  personalIncomeAmount: number; // Thu nhập cá nhân

  @Prop({ type: Number, required: true })
  longTermAssetAmount: number; // Tài sản dài hạn

  // ========== TỶ LỆ ĐÃ DÙNG (%) ==========
  @Prop({ type: Number, required: true })
  reinvestmentRatio: number;

  @Prop({ type: Number, required: true })
  safetyReserveRatio: number;

  @Prop({ type: Number, required: true })
  personalIncomeRatio: number;

  @Prop({ type: Number, required: true })
  longTermAssetRatio: number;

  // ========== THEO DÕI SỬ DỤNG ==========
  @Prop({ type: Number, default: 0 })
  reinvestmentUsed: number; // Đã dùng cho ads

  @Prop({ type: Number, default: 0 })
  safetyReserveUsed: number; // Đã rút từ dự phòng

  @Prop({ type: Number, default: 0 })
  personalIncomeWithdrawn: number; // Đã rút thu nhập

  @Prop({ type: Number, default: 0 })
  longTermAssetInvested: number; // Đã đầu tư dài hạn

  @Prop({ type: String })
  note?: string;

  @Prop({ type: Boolean, default: false })
  isAutoGenerated: boolean;
}

export const CapitalAllocationSnapshotSchema = SchemaFactory.createForClass(CapitalAllocationSnapshot);

// Index for quick date range queries
CapitalAllocationSnapshotSchema.index({ date: -1, policyName: 1 });
